package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/linuxuser586/gcpemu/internal/fault"
)

// providerEndpoints maps an OpenTofu google provider *_custom_endpoint
// setting to the gateway mount prefix and the provider's default base path.
var providerEndpoints = []struct{ setting, service, path string }{
	{"iam_custom_endpoint", "iam", "/iam/v1/"},
	{"iam_credentials_custom_endpoint", "iam", "/iamcredentials/v1/"},
	{"resource_manager_custom_endpoint", "iam", "/cloudresourcemanager/v1/"},
	{"resource_manager_v3_custom_endpoint", "iam", "/cloudresourcemanager/v3/"},
	{"storage_custom_endpoint", "gcs", "/storage/v1/"},
	{"pubsub_custom_endpoint", "pubsub", "/pubsub/v1/"},
	{"dns_custom_endpoint", "dns", "/dns/v1/"},
	{"artifact_registry_custom_endpoint", "ar", "/artifactregistry/v1/"},
	{"compute_custom_endpoint", "compute", "/compute/v1/"},
	{"container_custom_endpoint", "gke", "/container/v1/"},
	{"sql_custom_endpoint", "sql", "/sql/v1beta4/"},
}

func (o *rootOpts) tofuProviderCmd() *cobra.Command {
	var project, region string
	cmd := &cobra.Command{
		Use:   "tofu-provider",
		Short: "Print an OpenTofu provider \"google\" block pointing at the instance",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := o.load(cmd.Flags())
			if err != nil {
				return err
			}
			c, err := clientFor(cfg)
			if err != nil {
				return err
			}
			b, err := c.get("/_emu/v1/info")
			if err != nil {
				return err
			}
			var info struct{ Services []string }
			_ = json.Unmarshal(b, &info)
			running := map[string]bool{}
			for _, s := range info.Services {
				running[s] = true
			}
			out := cmd.OutOrStdout()
			fmt.Fprintf(out, "# Generated by `gcpemu tofu-provider` for instance %q.\n", cfg.Instance)
			fmt.Fprintln(out, `provider "google" {`)
			fmt.Fprintf(out, "  project      = %q\n", project)
			fmt.Fprintf(out, "  region       = %q\n", region)
			fmt.Fprintln(out, `  access_token = "owner" # accepted as the default principal`)
			fmt.Fprintln(out)
			for _, e := range providerEndpoints {
				if running[e.service] {
					fmt.Fprintf(out, "  %-36s = %q\n", e.setting, c.base+e.path)
				}
			}
			fmt.Fprintln(out, "}")
			return nil
		},
	}
	cmd.Flags().StringVar(&project, "project", "gcpemu-project", "project for the provider block")
	cmd.Flags().StringVar(&region, "region", "us-central1", "region for the provider block")
	return cmd
}

func (o *rootOpts) faultCmd() *cobra.Command {
	root := &cobra.Command{Use: "fault", Short: "Manage fault-injection rules"}
	var r fault.Rule
	var latency time.Duration
	add := &cobra.Command{
		Use:   "add",
		Short: "Add a fault-injection rule",
		RunE: func(cmd *cobra.Command, args []string) error {
			r.Latency = fault.Duration(latency)
			body, _ := json.Marshal(r)
			return o.adminCall(cmd, http.MethodPost, "/_emu/v1/faults", body)
		},
	}
	f := add.Flags()
	f.StringVar(&r.ID, "id", "", "rule ID (default generated)")
	f.StringVar(&r.Service, "service", "", "service name")
	f.StringVar(&r.Method, "method", "", "regexp on method (\"GET /storage/v1/b\" or \"/google.pubsub.v1.Publisher/Publish\")")
	f.StringVar(&r.Resource, "resource", "", "regexp on request path")
	f.StringVar(&r.Code, "code", "", "error code name, e.g. UNAVAILABLE")
	f.IntVar(&r.HTTPStatus, "http-status", 0, "override HTTP status")
	f.DurationVar(&latency, "latency", 0, "added latency")
	f.BoolVar(&r.Drop, "drop", false, "drop the connection")
	f.Float64Var(&r.Probability, "probability", 0, "probability in (0,1]; 0 = always")
	f.IntVar(&r.Count, "count", 0, "fire at most N times; 0 = unlimited")

	list := &cobra.Command{
		Use:   "list",
		Short: "List fault-injection rules",
		RunE: func(cmd *cobra.Command, args []string) error {
			return o.adminCall(cmd, http.MethodGet, "/_emu/v1/faults", nil)
		},
	}
	clearCmd := &cobra.Command{
		Use:   "clear [ID]",
		Short: "Remove one rule, or all rules",
		Args:  cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/_emu/v1/faults"
			if len(args) == 1 {
				path += "/" + args[0]
			}
			return o.adminCall(cmd, http.MethodDelete, path, nil)
		},
	}
	root.AddCommand(add, list, clearCmd)
	return root
}

// adminCall sends a request to the running instance's admin API and prints
// the response body.
func (o *rootOpts) adminCall(cmd *cobra.Command, method, path string, body []byte) error {
	cfg, err := o.load(cmd.Flags())
	if err != nil {
		return err
	}
	c, err := clientFor(cfg)
	if err != nil {
		return err
	}
	var rd io.Reader
	if body != nil {
		rd = bytes.NewReader(body)
	}
	req, err := http.NewRequest(method, c.base+path, rd)
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.http.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	b, _ := io.ReadAll(resp.Body)
	if resp.StatusCode >= 300 {
		return fmt.Errorf("%s", strings.TrimSpace(string(b)))
	}
	_, err = cmd.OutOrStdout().Write(b)
	return err
}
