/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/_emu/v1/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This document (also printed by `gcpemu admin openapi`). */
        get: operations["openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness of the gateway. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness per service (NFR-REL-003). */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instance identity, configuration summary and endpoints. */
        get: operations["info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listener addresses by endpoint name (as in endpoints.json). */
        get: operations["endpoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/env": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environment variables clients need (`gcpemu env`). */
        get: operations["env"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/hostmode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Host mode state (FR-CORE-043). */
        get: operations["hostMode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/containers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Containers the instance created (GKE nodes, Cloud SQL, NAT, ...). */
        get: operations["containers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a seed file idempotently (FR-CORE-011). */
        post: operations["seed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent stream of resource changes, Operation progress and Request log entries (FR-UI-006).
         * @description A `text/event-stream` that stays open. Each event has an `id`, an
         *     `event` type and one line of JSON `data`:
         *
         *     - `resource`: a ResourceChange, sent when a control-plane store key
         *       is written or deleted.
         *     - `operation`: an OperationChange, sent when an Operation of any
         *       Service (including Cloud DNS changes) is created, progresses,
         *       completes or is deleted.
         *     - `request`: a RequestEntry, sent for every Request log entry.
         *     - `reset`: `{}`; all state was replaced (`gcpemu reset`). Refetch
         *       everything.
         *     - `gap`: `{}`; only sent first on a resumed stream whose missed
         *       events are no longer retained or whose ID belongs to another
         *       process. Refetch everything.
         *
         *     Events are numbered per process. To resume, reconnect with the last
         *     `id` in `Last-Event-ID` (EventSource does this itself): missed
         *     events are replayed, or `gap` is sent. Idle streams carry a comment
         *     every 15 s. The server ends a stream whose client falls too far
         *     behind, and at shutdown; the `retry` field asks clients to
         *     reconnect after 1 s.
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent request log entries, oldest first (FR-CORE-061). */
        get: operations["requests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dump of the control-plane store. */
        get: operations["resources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/resources/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Number of resources of each type, per service (Web console dashboard).
         * @description Keys are service IDs and user-facing resource types named like the API's collections ("buckets", "subscriptions"), not store namespaces. Services that hold no resources of their own (cdn, nat) are absent.
         */
        get: operations["resourceCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wipe all state, keeping configuration (`gcpemu reset`). */
        post: operations["reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/time/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance the emulator clock (`gcpemu time advance`, FR-GCS-008). */
        post: operations["advanceTime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/faults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active fault injection rules (FR-CORE-060). */
        get: operations["listFaults"];
        put?: never;
        /** Add a fault injection rule. */
        post: operations["addFault"];
        /** Remove every fault injection rule. */
        delete: operations["clearFaults"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/faults/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove one fault injection rule. */
        delete: operations["removeFault"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shut the instance down gracefully (`gcpemu stop`). */
        post: operations["shutdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/cdn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cloud CDN cache statistics (cdn service). */
        get: operations["cdnStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/cdn/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the Cloud CDN cache (`gcpemu cdn purge`, FR-CDN-008). */
        post: operations["cdnPurge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_emu/v1/ca/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace the instance CA and re-issue managed certificates (`gcpemu ca rotate`; certs service). */
        post: operations["caRotate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Info: {
            instance: string;
            id: string;
            pid: number;
            version: string;
            /** @description Instance data directory. */
            dir: string;
            ephemeral: boolean;
            /** @enum {string} */
            iamMode: "off" | "audit" | "enforce";
            /** @description Referencing a project that does not exist is an error instead of creating it. */
            strictProjects: boolean;
            /** @description Whether the gateway serves the Web console under /console/. */
            console: boolean;
            /** @description Enabled services, in start order. */
            services: string[];
            endpoints: components["schemas"]["Endpoints"];
            runtime: components["schemas"]["RuntimeStatus"];
        };
        /** @description The container runtime the instance uses, or would use once a service needs one. Probed at most every few seconds. */
        RuntimeStatus: {
            /** @enum {string} */
            kind: "docker" | "podman" | "none";
            version?: string;
            reachable: boolean;
            /** @description Why the runtime is not reachable. */
            error?: string;
        };
        Container: {
            name: string;
            service?: string;
            resource?: string;
            role?: string;
            image: string;
            state: string;
        };
        ResourceCounts: {
            [key: string]: {
                [key: string]: number;
            };
        };
        /** @description Endpoint name ("gateway", "gcs", "lb:FORWARDING_RULE", ...) to host:port. */
        Endpoints: {
            [key: string]: string;
        };
        Readiness: {
            ready: boolean;
            services: {
                [key: string]: {
                    ready: boolean;
                    reason?: string;
                };
            };
        };
        /** @description Data of a `resource` event. */
        ResourceChange: {
            /** @description The namespace's first segment: a Service ID, or "core" for state the emulator owns (Projects in "core/projects"). */
            service: string;
            /** @description Store namespace */
            namespace: string;
            /** @description Store key within the namespace. */
            key: string;
            deleted?: boolean;
        };
        /** @description Data of an `operation` event. */
        OperationChange: {
            /** @description Service ID that owns the Operation. */
            service: string;
            /** @description Store namespace */
            namespace: string;
            /** @description The Operation's name for google.longrunning Operations, otherwise its store key (e.g. "P/OP" for Cloud SQL). */
            name: string;
            done: boolean;
            deleted?: boolean;
        };
        RequestEntry: {
            /** Format: date-time */
            time?: string;
            service?: string;
            /** @description http, grpc, dns, postgres, tcp, udp */
            protocol?: string;
            method?: string;
            resource?: string;
            principal?: string;
            /** @description HTTP status, gRPC code or DNS rcode; for connections 0 when admitted and 1 when refused. */
            status?: number;
            code?: string;
            latencyMs?: number;
        };
        FaultRule: {
            readonly id?: string;
            /** @description Emulator service name ("gcs" */
            service?: string;
            /** @description Regexp on the method ("GET /storage/v1/b", "/google.pubsub.v1.Publisher/Publish"). */
            method?: string;
            /** @description Regexp on the request path or resource. */
            resource?: string;
            /** @description Canonical error name to return */
            code?: string;
            /** @description Overrides the HTTP status for code. */
            httpStatus?: number;
            /** @description Delay added before handling */
            latency?: string;
            /** @description Close the connection without a response. */
            drop?: boolean;
            /** @description In (0,1]; 0 means always. */
            probability?: number;
            /** @description How many times the rule fires; 0 means unlimited. */
            count?: number;
            readonly fired?: number;
        };
    };
    responses: {
        /** @description The operation succeeded. */
        Status: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    status?: string;
                };
            };
        };
        /** @description The operation failed. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    openapi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3 document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The emulator is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ok";
                    };
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every enabled service is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description At least one service is not ready; its reason is given. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"];
                };
            };
        };
    };
    endpoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Endpoints. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Endpoints"];
                };
            };
        };
    };
    env: {
        parameters: {
            query?: {
                /** @description With true, write a bundle of the system roots plus the emulator CA and point SSL_CERT_FILE at it. */
                trust?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Variable name to value. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            500: components["responses"]["Error"];
        };
    };
    hostMode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host mode status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        enabled?: boolean;
                        state?: string;
                        error?: string;
                        /** @description Frontend container address (HTTPS :443, HTTP :80, DNS :53). */
                        ip?: string;
                        /** @description Host bridge interface the IP is reached through. */
                        interface?: string;
                        domains?: string[];
                        hosts?: string[];
                        caFile?: string;
                    };
                };
            };
        };
    };
    containers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Containers, sorted by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        containers: components["schemas"]["Container"][];
                    };
                };
            };
            500: components["responses"]["Error"];
        };
    };
    seed: {
        parameters: {
            query: {
                /** @description Seed file path on the emulator host. */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Status"];
            400: components["responses"]["Error"];
        };
    };
    events: {
        parameters: {
            query?: {
                /** @description As Last-Event-ID, for clients that cannot set headers. */
                lastEventId?: string;
            };
            header?: {
                /** @description ID of the last event received, to resume after it. */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example retry: 1000
                     *
                     *     id: lx2k9q1c-7
                     *     event: resource
                     *     data: {"service":"gcs","namespace":"gcs/buckets","key":"my-bucket"}
                     *
                     *     id: lx2k9q1c-8
                     *     event: request
                     *     data: {"time":"2026-10-08T12:00:00Z","service":"gcs","protocol":"http","method":"POST /storage/v1/b","status":200,"latencyMs":1.2}
                     */
                    "text/event-stream": string;
                };
            };
        };
    };
    requests: {
        parameters: {
            query?: {
                /** @description Only entries of this service. */
                service?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request log. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        requests?: components["schemas"]["RequestEntry"][];
                    };
                };
            };
        };
    };
    resources: {
        parameters: {
            query?: {
                /** @description Only this store namespace (e.g. "compute/natsink"). */
                namespace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Namespace to key to stored value (JSON, or a string for non-JSON values). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            500: components["responses"]["Error"];
        };
    };
    resourceCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service ID to resource type to count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceCounts"];
                };
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Status"];
            500: components["responses"]["Error"];
        };
    };
    advanceTime: {
        parameters: {
            query: {
                /** @description Non-negative Go duration, e.g. "24h". */
                by: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new emulator time. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        now?: string;
                    };
                };
            };
            400: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    listFaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        faults?: components["schemas"]["FaultRule"][];
                    };
                };
            };
        };
    };
    addFault: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaultRule"];
            };
        };
        responses: {
            /** @description The added rule with its ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FaultRule"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    clearFaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Status"];
        };
    };
    removeFault: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Status"];
            404: components["responses"]["Error"];
        };
    };
    shutdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["Status"];
        };
    };
    cdnStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cache usage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries?: number;
                        bytes?: number;
                        limitBytes?: number;
                    };
                };
            };
        };
    };
    cdnPurge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Number of entries removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        purged?: number;
                    };
                };
            };
        };
    };
    caRotate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The CA was rotated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "rotated";
                        /** @description Path of the new ca.pem. */
                        path?: string;
                    };
                };
            };
            /** @description The instance has no CA (Google JSON error envelope). */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rotation failed (Google JSON error envelope). */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
