// Code generated by apigen from googleapis/googleapis@462426382d347da63e69da7b02d908df2c26ecbe; DO NOT EDIT.

package apidef

const googleapisCommit = "462426382d347da63e69da7b02d908df2c26ecbe"

var protoServices = []*Service{
	{Name: "google.cloud.certificatemanager.v1.CertificateManager", File: "google/cloud/certificatemanager/v1/certificate_manager.proto", Methods: []*Method{
		{Name: "ListCertificates", Input: "google.cloud.certificatemanager.v1.ListCertificatesRequest", Output: "google.cloud.certificatemanager.v1.ListCertificatesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/certificates", ""}}},
		{Name: "GetCertificate", Input: "google.cloud.certificatemanager.v1.GetCertificateRequest", Output: "google.cloud.certificatemanager.v1.Certificate", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/certificates/*}", ""}}},
		{Name: "CreateCertificate", Input: "google.cloud.certificatemanager.v1.CreateCertificateRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/certificates", "certificate"}}},
		{Name: "UpdateCertificate", Input: "google.cloud.certificatemanager.v1.UpdateCertificateRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{certificate.name=projects/*/locations/*/certificates/*}", "certificate"}}},
		{Name: "DeleteCertificate", Input: "google.cloud.certificatemanager.v1.DeleteCertificateRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/certificates/*}", ""}}},
		{Name: "ListCertificateMaps", Input: "google.cloud.certificatemanager.v1.ListCertificateMapsRequest", Output: "google.cloud.certificatemanager.v1.ListCertificateMapsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/certificateMaps", ""}}},
		{Name: "GetCertificateMap", Input: "google.cloud.certificatemanager.v1.GetCertificateMapRequest", Output: "google.cloud.certificatemanager.v1.CertificateMap", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/certificateMaps/*}", ""}}},
		{Name: "CreateCertificateMap", Input: "google.cloud.certificatemanager.v1.CreateCertificateMapRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/certificateMaps", "certificate_map"}}},
		{Name: "UpdateCertificateMap", Input: "google.cloud.certificatemanager.v1.UpdateCertificateMapRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{certificate_map.name=projects/*/locations/*/certificateMaps/*}", "certificate_map"}}},
		{Name: "DeleteCertificateMap", Input: "google.cloud.certificatemanager.v1.DeleteCertificateMapRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/certificateMaps/*}", ""}}},
		{Name: "ListCertificateMapEntries", Input: "google.cloud.certificatemanager.v1.ListCertificateMapEntriesRequest", Output: "google.cloud.certificatemanager.v1.ListCertificateMapEntriesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/certificateMaps/*}/certificateMapEntries", ""}}},
		{Name: "GetCertificateMapEntry", Input: "google.cloud.certificatemanager.v1.GetCertificateMapEntryRequest", Output: "google.cloud.certificatemanager.v1.CertificateMapEntry", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/certificateMaps/*/certificateMapEntries/*}", ""}}},
		{Name: "CreateCertificateMapEntry", Input: "google.cloud.certificatemanager.v1.CreateCertificateMapEntryRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*/certificateMaps/*}/certificateMapEntries", "certificate_map_entry"}}},
		{Name: "UpdateCertificateMapEntry", Input: "google.cloud.certificatemanager.v1.UpdateCertificateMapEntryRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{certificate_map_entry.name=projects/*/locations/*/certificateMaps/*/certificateMapEntries/*}", "certificate_map_entry"}}},
		{Name: "DeleteCertificateMapEntry", Input: "google.cloud.certificatemanager.v1.DeleteCertificateMapEntryRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/certificateMaps/*/certificateMapEntries/*}", ""}}},
		{Name: "ListDnsAuthorizations", Input: "google.cloud.certificatemanager.v1.ListDnsAuthorizationsRequest", Output: "google.cloud.certificatemanager.v1.ListDnsAuthorizationsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/dnsAuthorizations", ""}}},
		{Name: "GetDnsAuthorization", Input: "google.cloud.certificatemanager.v1.GetDnsAuthorizationRequest", Output: "google.cloud.certificatemanager.v1.DnsAuthorization", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/dnsAuthorizations/*}", ""}}},
		{Name: "CreateDnsAuthorization", Input: "google.cloud.certificatemanager.v1.CreateDnsAuthorizationRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/dnsAuthorizations", "dns_authorization"}}},
		{Name: "UpdateDnsAuthorization", Input: "google.cloud.certificatemanager.v1.UpdateDnsAuthorizationRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{dns_authorization.name=projects/*/locations/*/dnsAuthorizations/*}", "dns_authorization"}}},
		{Name: "DeleteDnsAuthorization", Input: "google.cloud.certificatemanager.v1.DeleteDnsAuthorizationRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/dnsAuthorizations/*}", ""}}},
		{Name: "ListCertificateIssuanceConfigs", Input: "google.cloud.certificatemanager.v1.ListCertificateIssuanceConfigsRequest", Output: "google.cloud.certificatemanager.v1.ListCertificateIssuanceConfigsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/certificateIssuanceConfigs", ""}}},
		{Name: "GetCertificateIssuanceConfig", Input: "google.cloud.certificatemanager.v1.GetCertificateIssuanceConfigRequest", Output: "google.cloud.certificatemanager.v1.CertificateIssuanceConfig", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/certificateIssuanceConfigs/*}", ""}}},
		{Name: "CreateCertificateIssuanceConfig", Input: "google.cloud.certificatemanager.v1.CreateCertificateIssuanceConfigRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/certificateIssuanceConfigs", "certificate_issuance_config"}}},
		{Name: "DeleteCertificateIssuanceConfig", Input: "google.cloud.certificatemanager.v1.DeleteCertificateIssuanceConfigRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/certificateIssuanceConfigs/*}", ""}}},
		{Name: "ListTrustConfigs", Input: "google.cloud.certificatemanager.v1.ListTrustConfigsRequest", Output: "google.cloud.certificatemanager.v1.ListTrustConfigsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/trustConfigs", ""}}},
		{Name: "GetTrustConfig", Input: "google.cloud.certificatemanager.v1.GetTrustConfigRequest", Output: "google.cloud.certificatemanager.v1.TrustConfig", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/trustConfigs/*}", ""}}},
		{Name: "CreateTrustConfig", Input: "google.cloud.certificatemanager.v1.CreateTrustConfigRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/trustConfigs", "trust_config"}}},
		{Name: "UpdateTrustConfig", Input: "google.cloud.certificatemanager.v1.UpdateTrustConfigRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{trust_config.name=projects/*/locations/*/trustConfigs/*}", "trust_config"}}},
		{Name: "DeleteTrustConfig", Input: "google.cloud.certificatemanager.v1.DeleteTrustConfigRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/trustConfigs/*}", ""}}},
	}},
	{Name: "google.cloud.location.Locations", File: "google/cloud/location/locations.proto", Methods: []*Method{
		{Name: "ListLocations", Input: "google.cloud.location.ListLocationsRequest", Output: "google.cloud.location.ListLocationsResponse", HTTP: []Binding{{"GET", "/v1/{name=locations}", ""}, {"GET", "/v1/{name=projects/*}/locations", ""}}},
		{Name: "GetLocation", Input: "google.cloud.location.GetLocationRequest", Output: "google.cloud.location.Location", HTTP: []Binding{{"GET", "/v1/{name=locations/*}", ""}, {"GET", "/v1/{name=projects/*/locations/*}", ""}}},
	}},
	{Name: "google.cloud.networksecurity.v1.NetworkSecurity", File: "google/cloud/networksecurity/v1/network_security.proto", Methods: []*Method{
		{Name: "ListAuthorizationPolicies", Input: "google.cloud.networksecurity.v1.ListAuthorizationPoliciesRequest", Output: "google.cloud.networksecurity.v1.ListAuthorizationPoliciesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/authorizationPolicies", ""}}},
		{Name: "GetAuthorizationPolicy", Input: "google.cloud.networksecurity.v1.GetAuthorizationPolicyRequest", Output: "google.cloud.networksecurity.v1.AuthorizationPolicy", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/authorizationPolicies/*}", ""}}},
		{Name: "CreateAuthorizationPolicy", Input: "google.cloud.networksecurity.v1.CreateAuthorizationPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/authorizationPolicies", "authorization_policy"}}},
		{Name: "UpdateAuthorizationPolicy", Input: "google.cloud.networksecurity.v1.UpdateAuthorizationPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{authorization_policy.name=projects/*/locations/*/authorizationPolicies/*}", "authorization_policy"}}},
		{Name: "DeleteAuthorizationPolicy", Input: "google.cloud.networksecurity.v1.DeleteAuthorizationPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/authorizationPolicies/*}", ""}}},
		{Name: "ListBackendAuthenticationConfigs", Input: "google.cloud.networksecurity.v1.ListBackendAuthenticationConfigsRequest", Output: "google.cloud.networksecurity.v1.ListBackendAuthenticationConfigsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/backendAuthenticationConfigs", ""}}},
		{Name: "GetBackendAuthenticationConfig", Input: "google.cloud.networksecurity.v1.GetBackendAuthenticationConfigRequest", Output: "google.cloud.networksecurity.v1.BackendAuthenticationConfig", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/backendAuthenticationConfigs/*}", ""}}},
		{Name: "CreateBackendAuthenticationConfig", Input: "google.cloud.networksecurity.v1.CreateBackendAuthenticationConfigRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/backendAuthenticationConfigs", "backend_authentication_config"}}},
		{Name: "UpdateBackendAuthenticationConfig", Input: "google.cloud.networksecurity.v1.UpdateBackendAuthenticationConfigRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{backend_authentication_config.name=projects/*/locations/*/backendAuthenticationConfigs/*}", "backend_authentication_config"}}},
		{Name: "DeleteBackendAuthenticationConfig", Input: "google.cloud.networksecurity.v1.DeleteBackendAuthenticationConfigRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/backendAuthenticationConfigs/*}", ""}}},
		{Name: "ListServerTlsPolicies", Input: "google.cloud.networksecurity.v1.ListServerTlsPoliciesRequest", Output: "google.cloud.networksecurity.v1.ListServerTlsPoliciesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/serverTlsPolicies", ""}}},
		{Name: "GetServerTlsPolicy", Input: "google.cloud.networksecurity.v1.GetServerTlsPolicyRequest", Output: "google.cloud.networksecurity.v1.ServerTlsPolicy", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/serverTlsPolicies/*}", ""}}},
		{Name: "CreateServerTlsPolicy", Input: "google.cloud.networksecurity.v1.CreateServerTlsPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/serverTlsPolicies", "server_tls_policy"}}},
		{Name: "UpdateServerTlsPolicy", Input: "google.cloud.networksecurity.v1.UpdateServerTlsPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{server_tls_policy.name=projects/*/locations/*/serverTlsPolicies/*}", "server_tls_policy"}}},
		{Name: "DeleteServerTlsPolicy", Input: "google.cloud.networksecurity.v1.DeleteServerTlsPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/serverTlsPolicies/*}", ""}}},
		{Name: "ListClientTlsPolicies", Input: "google.cloud.networksecurity.v1.ListClientTlsPoliciesRequest", Output: "google.cloud.networksecurity.v1.ListClientTlsPoliciesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/clientTlsPolicies", ""}}},
		{Name: "GetClientTlsPolicy", Input: "google.cloud.networksecurity.v1.GetClientTlsPolicyRequest", Output: "google.cloud.networksecurity.v1.ClientTlsPolicy", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/clientTlsPolicies/*}", ""}}},
		{Name: "CreateClientTlsPolicy", Input: "google.cloud.networksecurity.v1.CreateClientTlsPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/clientTlsPolicies", "client_tls_policy"}}},
		{Name: "UpdateClientTlsPolicy", Input: "google.cloud.networksecurity.v1.UpdateClientTlsPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{client_tls_policy.name=projects/*/locations/*/clientTlsPolicies/*}", "client_tls_policy"}}},
		{Name: "DeleteClientTlsPolicy", Input: "google.cloud.networksecurity.v1.DeleteClientTlsPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/clientTlsPolicies/*}", ""}}},
		{Name: "ListGatewaySecurityPolicies", Input: "google.cloud.networksecurity.v1.ListGatewaySecurityPoliciesRequest", Output: "google.cloud.networksecurity.v1.ListGatewaySecurityPoliciesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/gatewaySecurityPolicies", ""}}},
		{Name: "GetGatewaySecurityPolicy", Input: "google.cloud.networksecurity.v1.GetGatewaySecurityPolicyRequest", Output: "google.cloud.networksecurity.v1.GatewaySecurityPolicy", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/gatewaySecurityPolicies/*}", ""}}},
		{Name: "CreateGatewaySecurityPolicy", Input: "google.cloud.networksecurity.v1.CreateGatewaySecurityPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/gatewaySecurityPolicies", "gateway_security_policy"}}},
		{Name: "UpdateGatewaySecurityPolicy", Input: "google.cloud.networksecurity.v1.UpdateGatewaySecurityPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{gateway_security_policy.name=projects/*/locations/*/gatewaySecurityPolicies/*}", "gateway_security_policy"}}},
		{Name: "DeleteGatewaySecurityPolicy", Input: "google.cloud.networksecurity.v1.DeleteGatewaySecurityPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/gatewaySecurityPolicies/*}", ""}}},
		{Name: "ListGatewaySecurityPolicyRules", Input: "google.cloud.networksecurity.v1.ListGatewaySecurityPolicyRulesRequest", Output: "google.cloud.networksecurity.v1.ListGatewaySecurityPolicyRulesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/gatewaySecurityPolicies/*}/rules", ""}}},
		{Name: "GetGatewaySecurityPolicyRule", Input: "google.cloud.networksecurity.v1.GetGatewaySecurityPolicyRuleRequest", Output: "google.cloud.networksecurity.v1.GatewaySecurityPolicyRule", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/gatewaySecurityPolicies/*/rules/*}", ""}}},
		{Name: "CreateGatewaySecurityPolicyRule", Input: "google.cloud.networksecurity.v1.CreateGatewaySecurityPolicyRuleRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*/gatewaySecurityPolicies/*}/rules", "gateway_security_policy_rule"}}},
		{Name: "UpdateGatewaySecurityPolicyRule", Input: "google.cloud.networksecurity.v1.UpdateGatewaySecurityPolicyRuleRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{gateway_security_policy_rule.name=projects/*/locations/*/gatewaySecurityPolicies/*/rules/*}", "gateway_security_policy_rule"}}},
		{Name: "DeleteGatewaySecurityPolicyRule", Input: "google.cloud.networksecurity.v1.DeleteGatewaySecurityPolicyRuleRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/gatewaySecurityPolicies/*/rules/*}", ""}}},
		{Name: "ListUrlLists", Input: "google.cloud.networksecurity.v1.ListUrlListsRequest", Output: "google.cloud.networksecurity.v1.ListUrlListsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/urlLists", ""}}},
		{Name: "GetUrlList", Input: "google.cloud.networksecurity.v1.GetUrlListRequest", Output: "google.cloud.networksecurity.v1.UrlList", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/urlLists/*}", ""}}},
		{Name: "CreateUrlList", Input: "google.cloud.networksecurity.v1.CreateUrlListRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/urlLists", "url_list"}}},
		{Name: "UpdateUrlList", Input: "google.cloud.networksecurity.v1.UpdateUrlListRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{url_list.name=projects/*/locations/*/urlLists/*}", "url_list"}}},
		{Name: "DeleteUrlList", Input: "google.cloud.networksecurity.v1.DeleteUrlListRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/urlLists/*}", ""}}},
		{Name: "ListTlsInspectionPolicies", Input: "google.cloud.networksecurity.v1.ListTlsInspectionPoliciesRequest", Output: "google.cloud.networksecurity.v1.ListTlsInspectionPoliciesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/tlsInspectionPolicies", ""}}},
		{Name: "GetTlsInspectionPolicy", Input: "google.cloud.networksecurity.v1.GetTlsInspectionPolicyRequest", Output: "google.cloud.networksecurity.v1.TlsInspectionPolicy", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/tlsInspectionPolicies/*}", ""}}},
		{Name: "CreateTlsInspectionPolicy", Input: "google.cloud.networksecurity.v1.CreateTlsInspectionPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/tlsInspectionPolicies", "tls_inspection_policy"}}},
		{Name: "UpdateTlsInspectionPolicy", Input: "google.cloud.networksecurity.v1.UpdateTlsInspectionPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{tls_inspection_policy.name=projects/*/locations/*/tlsInspectionPolicies/*}", "tls_inspection_policy"}}},
		{Name: "DeleteTlsInspectionPolicy", Input: "google.cloud.networksecurity.v1.DeleteTlsInspectionPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/tlsInspectionPolicies/*}", ""}}},
		{Name: "ListAuthzPolicies", Input: "google.cloud.networksecurity.v1.ListAuthzPoliciesRequest", Output: "google.cloud.networksecurity.v1.ListAuthzPoliciesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/authzPolicies", ""}}},
		{Name: "GetAuthzPolicy", Input: "google.cloud.networksecurity.v1.GetAuthzPolicyRequest", Output: "google.cloud.networksecurity.v1.AuthzPolicy", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/authzPolicies/*}", ""}}},
		{Name: "CreateAuthzPolicy", Input: "google.cloud.networksecurity.v1.CreateAuthzPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/authzPolicies", "authz_policy"}}},
		{Name: "UpdateAuthzPolicy", Input: "google.cloud.networksecurity.v1.UpdateAuthzPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"PATCH", "/v1/{authz_policy.name=projects/*/locations/*/authzPolicies/*}", "authz_policy"}}},
		{Name: "DeleteAuthzPolicy", Input: "google.cloud.networksecurity.v1.DeleteAuthzPolicyRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/authzPolicies/*}", ""}}},
	}},
	{Name: "google.container.v1.ClusterManager", File: "google/container/v1/cluster_service.proto", Methods: []*Method{
		{Name: "ListClusters", Input: "google.container.v1.ListClustersRequest", Output: "google.container.v1.ListClustersResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/clusters", ""}, {"GET", "/v1/projects/{project_id}/zones/{zone}/clusters", ""}}},
		{Name: "GetCluster", Input: "google.container.v1.GetClusterRequest", Output: "google.container.v1.Cluster", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/clusters/*}", ""}, {"GET", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}", ""}}},
		{Name: "CreateCluster", Input: "google.container.v1.CreateClusterRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/clusters", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters", "*"}}},
		{Name: "UpdateCluster", Input: "google.container.v1.UpdateClusterRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"PUT", "/v1/{name=projects/*/locations/*/clusters/*}", "*"}, {"PUT", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}", "*"}}},
		{Name: "UpdateNodePool", Input: "google.container.v1.UpdateNodePoolRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"PUT", "/v1/{name=projects/*/locations/*/clusters/*/nodePools/*}", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/nodePools/{node_pool_id}/update", "*"}}},
		{Name: "SetNodePoolAutoscaling", Input: "google.container.v1.SetNodePoolAutoscalingRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*/nodePools/*}:setAutoscaling", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/nodePools/{node_pool_id}/autoscaling", "*"}}},
		{Name: "SetLoggingService", Input: "google.container.v1.SetLoggingServiceRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:setLogging", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/logging", "*"}}},
		{Name: "SetMonitoringService", Input: "google.container.v1.SetMonitoringServiceRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:setMonitoring", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/monitoring", "*"}}},
		{Name: "SetAddonsConfig", Input: "google.container.v1.SetAddonsConfigRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:setAddons", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/addons", "*"}}},
		{Name: "SetLocations", Input: "google.container.v1.SetLocationsRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:setLocations", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/locations", "*"}}},
		{Name: "UpdateMaster", Input: "google.container.v1.UpdateMasterRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:updateMaster", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/master", "*"}}},
		{Name: "SetMasterAuth", Input: "google.container.v1.SetMasterAuthRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:setMasterAuth", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}:setMasterAuth", "*"}}},
		{Name: "DeleteCluster", Input: "google.container.v1.DeleteClusterRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/clusters/*}", ""}, {"DELETE", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}", ""}}},
		{Name: "ListOperations", Input: "google.container.v1.ListOperationsRequest", Output: "google.container.v1.ListOperationsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/operations", ""}, {"GET", "/v1/projects/{project_id}/zones/{zone}/operations", ""}}},
		{Name: "GetOperation", Input: "google.container.v1.GetOperationRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/operations/*}", ""}, {"GET", "/v1/projects/{project_id}/zones/{zone}/operations/{operation_id}", ""}}},
		{Name: "CancelOperation", Input: "google.container.v1.CancelOperationRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/operations/*}:cancel", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/operations/{operation_id}:cancel", "*"}}},
		{Name: "GetServerConfig", Input: "google.container.v1.GetServerConfigRequest", Output: "google.container.v1.ServerConfig", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*}/serverConfig", ""}, {"GET", "/v1/projects/{project_id}/zones/{zone}/serverconfig", ""}}},
		{Name: "GetJSONWebKeys", Input: "google.container.v1.GetJSONWebKeysRequest", Output: "google.container.v1.GetJSONWebKeysResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/clusters/*}/jwks", ""}}},
		{Name: "ListNodePools", Input: "google.container.v1.ListNodePoolsRequest", Output: "google.container.v1.ListNodePoolsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/clusters/*}/nodePools", ""}, {"GET", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/nodePools", ""}}},
		{Name: "GetNodePool", Input: "google.container.v1.GetNodePoolRequest", Output: "google.container.v1.NodePool", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/clusters/*/nodePools/*}", ""}, {"GET", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/nodePools/{node_pool_id}", ""}}},
		{Name: "CreateNodePool", Input: "google.container.v1.CreateNodePoolRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*/clusters/*}/nodePools", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/nodePools", "*"}}},
		{Name: "DeleteNodePool", Input: "google.container.v1.DeleteNodePoolRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/clusters/*/nodePools/*}", ""}, {"DELETE", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/nodePools/{node_pool_id}", ""}}},
		{Name: "CompleteNodePoolUpgrade", Input: "google.container.v1.CompleteNodePoolUpgradeRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*/nodePools/*}:completeUpgrade", "*"}}},
		{Name: "RollbackNodePoolUpgrade", Input: "google.container.v1.RollbackNodePoolUpgradeRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*/nodePools/*}:rollback", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/nodePools/{node_pool_id}:rollback", "*"}}},
		{Name: "SetNodePoolManagement", Input: "google.container.v1.SetNodePoolManagementRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*/nodePools/*}:setManagement", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/nodePools/{node_pool_id}/setManagement", "*"}}},
		{Name: "SetLabels", Input: "google.container.v1.SetLabelsRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:setResourceLabels", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/resourceLabels", "*"}}},
		{Name: "SetLegacyAbac", Input: "google.container.v1.SetLegacyAbacRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:setLegacyAbac", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/legacyAbac", "*"}}},
		{Name: "StartIPRotation", Input: "google.container.v1.StartIPRotationRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:startIpRotation", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}:startIpRotation", "*"}}},
		{Name: "CompleteIPRotation", Input: "google.container.v1.CompleteIPRotationRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:completeIpRotation", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}:completeIpRotation", "*"}}},
		{Name: "SetNodePoolSize", Input: "google.container.v1.SetNodePoolSizeRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*/nodePools/*}:setSize", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}/nodePools/{node_pool_id}/setSize", "*"}}},
		{Name: "SetNetworkPolicy", Input: "google.container.v1.SetNetworkPolicyRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:setNetworkPolicy", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}:setNetworkPolicy", "*"}}},
		{Name: "SetMaintenancePolicy", Input: "google.container.v1.SetMaintenancePolicyRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:setMaintenancePolicy", "*"}, {"POST", "/v1/projects/{project_id}/zones/{zone}/clusters/{cluster_id}:setMaintenancePolicy", "*"}}},
		{Name: "ListUsableSubnetworks", Input: "google.container.v1.ListUsableSubnetworksRequest", Output: "google.container.v1.ListUsableSubnetworksResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*}/aggregated/usableSubnetworks", ""}}},
		{Name: "CheckAutopilotCompatibility", Input: "google.container.v1.CheckAutopilotCompatibilityRequest", Output: "google.container.v1.CheckAutopilotCompatibilityResponse", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/clusters/*}:checkAutopilotCompatibility", ""}}},
		{Name: "FetchClusterUpgradeInfo", Input: "google.container.v1.FetchClusterUpgradeInfoRequest", Output: "google.container.v1.ClusterUpgradeInfo", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/clusters/*}:fetchClusterUpgradeInfo", ""}, {"GET", "/v1/{name=projects/*/zones/*/clusters/*}:fetchClusterUpgradeInfo", ""}}},
		{Name: "FetchNodePoolUpgradeInfo", Input: "google.container.v1.FetchNodePoolUpgradeInfoRequest", Output: "google.container.v1.NodePoolUpgradeInfo", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/clusters/*/nodePools/*}:fetchNodePoolUpgradeInfo", ""}, {"GET", "/v1/{name=projects/*/zones/*/clusters/*/nodePools/*}:fetchNodePoolUpgradeInfo", ""}}},
		{Name: "CompleteControlPlaneUpgrade", Input: "google.container.v1.CompleteControlPlaneUpgradeRequest", Output: "google.container.v1.Operation", HTTP: []Binding{{"POST", "/v1/{name=projects/*/locations/*/clusters/*}:completeControlPlaneUpgrade", "*"}, {"POST", "/v1/{name=projects/*/zones/*/clusters/*}:completeControlPlaneUpgrade", "*"}}},
	}},
	{Name: "google.devtools.artifactregistry.v1.ArtifactRegistry", File: "google/devtools/artifactregistry/v1/service.proto", Methods: []*Method{
		{Name: "ListDockerImages", Input: "google.devtools.artifactregistry.v1.ListDockerImagesRequest", Output: "google.devtools.artifactregistry.v1.ListDockerImagesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/repositories/*}/dockerImages", ""}}},
		{Name: "GetDockerImage", Input: "google.devtools.artifactregistry.v1.GetDockerImageRequest", Output: "google.devtools.artifactregistry.v1.DockerImage", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*/dockerImages/*}", ""}}},
		{Name: "ListMavenArtifacts", Input: "google.devtools.artifactregistry.v1.ListMavenArtifactsRequest", Output: "google.devtools.artifactregistry.v1.ListMavenArtifactsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/repositories/*}/mavenArtifacts", ""}}},
		{Name: "GetMavenArtifact", Input: "google.devtools.artifactregistry.v1.GetMavenArtifactRequest", Output: "google.devtools.artifactregistry.v1.MavenArtifact", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*/mavenArtifacts/*}", ""}}},
		{Name: "ListNpmPackages", Input: "google.devtools.artifactregistry.v1.ListNpmPackagesRequest", Output: "google.devtools.artifactregistry.v1.ListNpmPackagesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/repositories/*}/npmPackages", ""}}},
		{Name: "GetNpmPackage", Input: "google.devtools.artifactregistry.v1.GetNpmPackageRequest", Output: "google.devtools.artifactregistry.v1.NpmPackage", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*/npmPackages/*}", ""}}},
		{Name: "ListPythonPackages", Input: "google.devtools.artifactregistry.v1.ListPythonPackagesRequest", Output: "google.devtools.artifactregistry.v1.ListPythonPackagesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/repositories/*}/pythonPackages", ""}}},
		{Name: "GetPythonPackage", Input: "google.devtools.artifactregistry.v1.GetPythonPackageRequest", Output: "google.devtools.artifactregistry.v1.PythonPackage", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*/pythonPackages/*}", ""}}},
		{Name: "ImportAptArtifacts", Input: "google.devtools.artifactregistry.v1.ImportAptArtifactsRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*/repositories/*}/aptArtifacts:import", "*"}}},
		{Name: "ImportYumArtifacts", Input: "google.devtools.artifactregistry.v1.ImportYumArtifactsRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*/repositories/*}/yumArtifacts:import", "*"}}},
		{Name: "ListRepositories", Input: "google.devtools.artifactregistry.v1.ListRepositoriesRequest", Output: "google.devtools.artifactregistry.v1.ListRepositoriesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*}/repositories", ""}}},
		{Name: "GetRepository", Input: "google.devtools.artifactregistry.v1.GetRepositoryRequest", Output: "google.devtools.artifactregistry.v1.Repository", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*}", ""}}},
		{Name: "CreateRepository", Input: "google.devtools.artifactregistry.v1.CreateRepositoryRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*}/repositories", "repository"}}},
		{Name: "UpdateRepository", Input: "google.devtools.artifactregistry.v1.UpdateRepositoryRequest", Output: "google.devtools.artifactregistry.v1.Repository", HTTP: []Binding{{"PATCH", "/v1/{repository.name=projects/*/locations/*/repositories/*}", "repository"}}},
		{Name: "DeleteRepository", Input: "google.devtools.artifactregistry.v1.DeleteRepositoryRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/repositories/*}", ""}}},
		{Name: "ListPackages", Input: "google.devtools.artifactregistry.v1.ListPackagesRequest", Output: "google.devtools.artifactregistry.v1.ListPackagesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/repositories/*}/packages", ""}}},
		{Name: "GetPackage", Input: "google.devtools.artifactregistry.v1.GetPackageRequest", Output: "google.devtools.artifactregistry.v1.Package", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*/packages/*}", ""}}},
		{Name: "DeletePackage", Input: "google.devtools.artifactregistry.v1.DeletePackageRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/repositories/*/packages/*}", ""}}},
		{Name: "ListVersions", Input: "google.devtools.artifactregistry.v1.ListVersionsRequest", Output: "google.devtools.artifactregistry.v1.ListVersionsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/repositories/*/packages/*}/versions", ""}}},
		{Name: "GetVersion", Input: "google.devtools.artifactregistry.v1.GetVersionRequest", Output: "google.devtools.artifactregistry.v1.Version", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*/packages/*/versions/*}", ""}}},
		{Name: "DeleteVersion", Input: "google.devtools.artifactregistry.v1.DeleteVersionRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/repositories/*/packages/*/versions/*}", ""}}},
		{Name: "BatchDeleteVersions", Input: "google.devtools.artifactregistry.v1.BatchDeleteVersionsRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*/repositories/*/packages/*}/versions:batchDelete", "*"}}},
		{Name: "UpdateVersion", Input: "google.devtools.artifactregistry.v1.UpdateVersionRequest", Output: "google.devtools.artifactregistry.v1.Version", HTTP: []Binding{{"PATCH", "/v1/{version.name=projects/*/locations/*/repositories/*/packages/*/versions/*}", "version"}}},
		{Name: "ListFiles", Input: "google.devtools.artifactregistry.v1.ListFilesRequest", Output: "google.devtools.artifactregistry.v1.ListFilesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/repositories/*}/files", ""}}},
		{Name: "GetFile", Input: "google.devtools.artifactregistry.v1.GetFileRequest", Output: "google.devtools.artifactregistry.v1.File", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*/files/**}", ""}}},
		{Name: "DeleteFile", Input: "google.devtools.artifactregistry.v1.DeleteFileRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/repositories/*/files/*}", ""}}},
		{Name: "UpdateFile", Input: "google.devtools.artifactregistry.v1.UpdateFileRequest", Output: "google.devtools.artifactregistry.v1.File", HTTP: []Binding{{"PATCH", "/v1/{file.name=projects/*/locations/*/repositories/*/files/*}", "file"}}},
		{Name: "ListTags", Input: "google.devtools.artifactregistry.v1.ListTagsRequest", Output: "google.devtools.artifactregistry.v1.ListTagsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/repositories/*/packages/*}/tags", ""}}},
		{Name: "GetTag", Input: "google.devtools.artifactregistry.v1.GetTagRequest", Output: "google.devtools.artifactregistry.v1.Tag", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*/packages/*/tags/*}", ""}}},
		{Name: "CreateTag", Input: "google.devtools.artifactregistry.v1.CreateTagRequest", Output: "google.devtools.artifactregistry.v1.Tag", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*/repositories/*/packages/*}/tags", "tag"}}},
		{Name: "UpdateTag", Input: "google.devtools.artifactregistry.v1.UpdateTagRequest", Output: "google.devtools.artifactregistry.v1.Tag", HTTP: []Binding{{"PATCH", "/v1/{tag.name=projects/*/locations/*/repositories/*/packages/*/tags/*}", "tag"}}},
		{Name: "DeleteTag", Input: "google.devtools.artifactregistry.v1.DeleteTagRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/repositories/*/packages/*/tags/*}", ""}}},
		{Name: "CreateRule", Input: "google.devtools.artifactregistry.v1.CreateRuleRequest", Output: "google.devtools.artifactregistry.v1.Rule", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*/repositories/*}/rules", "rule"}}},
		{Name: "ListRules", Input: "google.devtools.artifactregistry.v1.ListRulesRequest", Output: "google.devtools.artifactregistry.v1.ListRulesResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/repositories/*}/rules", ""}}},
		{Name: "GetRule", Input: "google.devtools.artifactregistry.v1.GetRuleRequest", Output: "google.devtools.artifactregistry.v1.Rule", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*/rules/*}", ""}}},
		{Name: "UpdateRule", Input: "google.devtools.artifactregistry.v1.UpdateRuleRequest", Output: "google.devtools.artifactregistry.v1.Rule", HTTP: []Binding{{"PATCH", "/v1/{rule.name=projects/*/locations/*/repositories/*/rules/*}", "rule"}}},
		{Name: "DeleteRule", Input: "google.devtools.artifactregistry.v1.DeleteRuleRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/repositories/*/rules/*}", ""}}},
		{Name: "SetIamPolicy", Input: "google.iam.v1.SetIamPolicyRequest", Output: "google.iam.v1.Policy", HTTP: []Binding{{"POST", "/v1/{resource=projects/*/locations/*/repositories/*}:setIamPolicy", "*"}}},
		{Name: "GetIamPolicy", Input: "google.iam.v1.GetIamPolicyRequest", Output: "google.iam.v1.Policy", HTTP: []Binding{{"GET", "/v1/{resource=projects/*/locations/*/repositories/*}:getIamPolicy", ""}}},
		{Name: "TestIamPermissions", Input: "google.iam.v1.TestIamPermissionsRequest", Output: "google.iam.v1.TestIamPermissionsResponse", HTTP: []Binding{{"POST", "/v1/{resource=projects/*/locations/*/repositories/*}:testIamPermissions", "*"}}},
		{Name: "GetProjectSettings", Input: "google.devtools.artifactregistry.v1.GetProjectSettingsRequest", Output: "google.devtools.artifactregistry.v1.ProjectSettings", HTTP: []Binding{{"GET", "/v1/{name=projects/*/projectSettings}", ""}}},
		{Name: "UpdateProjectSettings", Input: "google.devtools.artifactregistry.v1.UpdateProjectSettingsRequest", Output: "google.devtools.artifactregistry.v1.ProjectSettings", HTTP: []Binding{{"PATCH", "/v1/{project_settings.name=projects/*/projectSettings}", "project_settings"}}},
		{Name: "GetVPCSCConfig", Input: "google.devtools.artifactregistry.v1.GetVPCSCConfigRequest", Output: "google.devtools.artifactregistry.v1.VPCSCConfig", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/vpcscConfig}", ""}}},
		{Name: "UpdateVPCSCConfig", Input: "google.devtools.artifactregistry.v1.UpdateVPCSCConfigRequest", Output: "google.devtools.artifactregistry.v1.VPCSCConfig", HTTP: []Binding{{"PATCH", "/v1/{vpcsc_config.name=projects/*/locations/*/vpcscConfig}", "vpcsc_config"}}},
		{Name: "UpdatePackage", Input: "google.devtools.artifactregistry.v1.UpdatePackageRequest", Output: "google.devtools.artifactregistry.v1.Package", HTTP: []Binding{{"PATCH", "/v1/{package.name=projects/*/locations/*/repositories/*/packages/*}", "package"}}},
		{Name: "ListAttachments", Input: "google.devtools.artifactregistry.v1.ListAttachmentsRequest", Output: "google.devtools.artifactregistry.v1.ListAttachmentsResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*/locations/*/repositories/*}/attachments", ""}}},
		{Name: "GetAttachment", Input: "google.devtools.artifactregistry.v1.GetAttachmentRequest", Output: "google.devtools.artifactregistry.v1.Attachment", HTTP: []Binding{{"GET", "/v1/{name=projects/*/locations/*/repositories/*/attachments/*}", ""}}},
		{Name: "CreateAttachment", Input: "google.devtools.artifactregistry.v1.CreateAttachmentRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{parent=projects/*/locations/*/repositories/*}/attachments", "attachment"}}},
		{Name: "DeleteAttachment", Input: "google.devtools.artifactregistry.v1.DeleteAttachmentRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/locations/*/repositories/*/attachments/*}", ""}}},
		{Name: "ExportArtifact", Input: "google.devtools.artifactregistry.v1.ExportArtifactRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"POST", "/v1/{repository=projects/*/locations/*/repositories/*}:exportArtifact", "*"}}},
	}},
	{Name: "google.iam.credentials.v1.IAMCredentials", File: "google/iam/credentials/v1/iamcredentials.proto", Methods: []*Method{
		{Name: "GenerateAccessToken", Input: "google.iam.credentials.v1.GenerateAccessTokenRequest", Output: "google.iam.credentials.v1.GenerateAccessTokenResponse", HTTP: []Binding{{"POST", "/v1/{name=projects/*/serviceAccounts/*}:generateAccessToken", "*"}}},
		{Name: "GenerateIdToken", Input: "google.iam.credentials.v1.GenerateIdTokenRequest", Output: "google.iam.credentials.v1.GenerateIdTokenResponse", HTTP: []Binding{{"POST", "/v1/{name=projects/*/serviceAccounts/*}:generateIdToken", "*"}}},
		{Name: "SignBlob", Input: "google.iam.credentials.v1.SignBlobRequest", Output: "google.iam.credentials.v1.SignBlobResponse", HTTP: []Binding{{"POST", "/v1/{name=projects/*/serviceAccounts/*}:signBlob", "*"}}},
		{Name: "SignJwt", Input: "google.iam.credentials.v1.SignJwtRequest", Output: "google.iam.credentials.v1.SignJwtResponse", HTTP: []Binding{{"POST", "/v1/{name=projects/*/serviceAccounts/*}:signJwt", "*"}}},
	}},
	{Name: "google.iam.v1.IAMPolicy", File: "google/iam/v1/iam_policy.proto", Methods: []*Method{
		{Name: "SetIamPolicy", Input: "google.iam.v1.SetIamPolicyRequest", Output: "google.iam.v1.Policy", HTTP: []Binding{{"POST", "/v1/{resource=**}:setIamPolicy", "*"}}},
		{Name: "GetIamPolicy", Input: "google.iam.v1.GetIamPolicyRequest", Output: "google.iam.v1.Policy", HTTP: []Binding{{"POST", "/v1/{resource=**}:getIamPolicy", "*"}}},
		{Name: "TestIamPermissions", Input: "google.iam.v1.TestIamPermissionsRequest", Output: "google.iam.v1.TestIamPermissionsResponse", HTTP: []Binding{{"POST", "/v1/{resource=**}:testIamPermissions", "*"}}},
	}},
	{Name: "google.longrunning.Operations", File: "google/longrunning/operations.proto", Methods: []*Method{
		{Name: "ListOperations", Input: "google.longrunning.ListOperationsRequest", Output: "google.longrunning.ListOperationsResponse", HTTP: []Binding{{"GET", "/v1/{name=operations}", ""}}},
		{Name: "GetOperation", Input: "google.longrunning.GetOperationRequest", Output: "google.longrunning.Operation", HTTP: []Binding{{"GET", "/v1/{name=operations/**}", ""}}},
		{Name: "DeleteOperation", Input: "google.longrunning.DeleteOperationRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"DELETE", "/v1/{name=operations/**}", ""}}},
		{Name: "CancelOperation", Input: "google.longrunning.CancelOperationRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"POST", "/v1/{name=operations/**}:cancel", "*"}}},
		{Name: "WaitOperation", Input: "google.longrunning.WaitOperationRequest", Output: "google.longrunning.Operation"},
	}},
	{Name: "google.pubsub.v1.Publisher", File: "google/pubsub/v1/pubsub.proto", Methods: []*Method{
		{Name: "CreateTopic", Input: "google.pubsub.v1.Topic", Output: "google.pubsub.v1.Topic", HTTP: []Binding{{"PUT", "/v1/{name=projects/*/topics/*}", "*"}}},
		{Name: "UpdateTopic", Input: "google.pubsub.v1.UpdateTopicRequest", Output: "google.pubsub.v1.Topic", HTTP: []Binding{{"PATCH", "/v1/{topic.name=projects/*/topics/*}", "*"}}},
		{Name: "Publish", Input: "google.pubsub.v1.PublishRequest", Output: "google.pubsub.v1.PublishResponse", HTTP: []Binding{{"POST", "/v1/{topic=projects/*/topics/*}:publish", "*"}}},
		{Name: "GetTopic", Input: "google.pubsub.v1.GetTopicRequest", Output: "google.pubsub.v1.Topic", HTTP: []Binding{{"GET", "/v1/{topic=projects/*/topics/*}", ""}}},
		{Name: "ListTopics", Input: "google.pubsub.v1.ListTopicsRequest", Output: "google.pubsub.v1.ListTopicsResponse", HTTP: []Binding{{"GET", "/v1/{project=projects/*}/topics", ""}}},
		{Name: "ListTopicSubscriptions", Input: "google.pubsub.v1.ListTopicSubscriptionsRequest", Output: "google.pubsub.v1.ListTopicSubscriptionsResponse", HTTP: []Binding{{"GET", "/v1/{topic=projects/*/topics/*}/subscriptions", ""}}},
		{Name: "ListTopicSnapshots", Input: "google.pubsub.v1.ListTopicSnapshotsRequest", Output: "google.pubsub.v1.ListTopicSnapshotsResponse", HTTP: []Binding{{"GET", "/v1/{topic=projects/*/topics/*}/snapshots", ""}}},
		{Name: "DeleteTopic", Input: "google.pubsub.v1.DeleteTopicRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"DELETE", "/v1/{topic=projects/*/topics/*}", ""}}},
		{Name: "DetachSubscription", Input: "google.pubsub.v1.DetachSubscriptionRequest", Output: "google.pubsub.v1.DetachSubscriptionResponse", HTTP: []Binding{{"POST", "/v1/{subscription=projects/*/subscriptions/*}:detach", ""}}},
	}},
	{Name: "google.pubsub.v1.Subscriber", File: "google/pubsub/v1/pubsub.proto", Methods: []*Method{
		{Name: "CreateSubscription", Input: "google.pubsub.v1.Subscription", Output: "google.pubsub.v1.Subscription", HTTP: []Binding{{"PUT", "/v1/{name=projects/*/subscriptions/*}", "*"}}},
		{Name: "GetSubscription", Input: "google.pubsub.v1.GetSubscriptionRequest", Output: "google.pubsub.v1.Subscription", HTTP: []Binding{{"GET", "/v1/{subscription=projects/*/subscriptions/*}", ""}}},
		{Name: "UpdateSubscription", Input: "google.pubsub.v1.UpdateSubscriptionRequest", Output: "google.pubsub.v1.Subscription", HTTP: []Binding{{"PATCH", "/v1/{subscription.name=projects/*/subscriptions/*}", "*"}}},
		{Name: "ListSubscriptions", Input: "google.pubsub.v1.ListSubscriptionsRequest", Output: "google.pubsub.v1.ListSubscriptionsResponse", HTTP: []Binding{{"GET", "/v1/{project=projects/*}/subscriptions", ""}}},
		{Name: "DeleteSubscription", Input: "google.pubsub.v1.DeleteSubscriptionRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"DELETE", "/v1/{subscription=projects/*/subscriptions/*}", ""}}},
		{Name: "ModifyAckDeadline", Input: "google.pubsub.v1.ModifyAckDeadlineRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"POST", "/v1/{subscription=projects/*/subscriptions/*}:modifyAckDeadline", "*"}}},
		{Name: "Acknowledge", Input: "google.pubsub.v1.AcknowledgeRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"POST", "/v1/{subscription=projects/*/subscriptions/*}:acknowledge", "*"}}},
		{Name: "Pull", Input: "google.pubsub.v1.PullRequest", Output: "google.pubsub.v1.PullResponse", HTTP: []Binding{{"POST", "/v1/{subscription=projects/*/subscriptions/*}:pull", "*"}}},
		{Name: "StreamingPull", Input: "google.pubsub.v1.StreamingPullRequest", Output: "google.pubsub.v1.StreamingPullResponse"},
		{Name: "ModifyPushConfig", Input: "google.pubsub.v1.ModifyPushConfigRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"POST", "/v1/{subscription=projects/*/subscriptions/*}:modifyPushConfig", "*"}}},
		{Name: "GetSnapshot", Input: "google.pubsub.v1.GetSnapshotRequest", Output: "google.pubsub.v1.Snapshot", HTTP: []Binding{{"GET", "/v1/{snapshot=projects/*/snapshots/*}", ""}}},
		{Name: "ListSnapshots", Input: "google.pubsub.v1.ListSnapshotsRequest", Output: "google.pubsub.v1.ListSnapshotsResponse", HTTP: []Binding{{"GET", "/v1/{project=projects/*}/snapshots", ""}}},
		{Name: "CreateSnapshot", Input: "google.pubsub.v1.CreateSnapshotRequest", Output: "google.pubsub.v1.Snapshot", HTTP: []Binding{{"PUT", "/v1/{name=projects/*/snapshots/*}", "*"}}},
		{Name: "UpdateSnapshot", Input: "google.pubsub.v1.UpdateSnapshotRequest", Output: "google.pubsub.v1.Snapshot", HTTP: []Binding{{"PATCH", "/v1/{snapshot.name=projects/*/snapshots/*}", "*"}}},
		{Name: "DeleteSnapshot", Input: "google.pubsub.v1.DeleteSnapshotRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"DELETE", "/v1/{snapshot=projects/*/snapshots/*}", ""}}},
		{Name: "Seek", Input: "google.pubsub.v1.SeekRequest", Output: "google.pubsub.v1.SeekResponse", HTTP: []Binding{{"POST", "/v1/{subscription=projects/*/subscriptions/*}:seek", "*"}}},
	}},
	{Name: "google.pubsub.v1.SchemaService", File: "google/pubsub/v1/schema.proto", Methods: []*Method{
		{Name: "CreateSchema", Input: "google.pubsub.v1.CreateSchemaRequest", Output: "google.pubsub.v1.Schema", HTTP: []Binding{{"POST", "/v1/{parent=projects/*}/schemas", "schema"}}},
		{Name: "GetSchema", Input: "google.pubsub.v1.GetSchemaRequest", Output: "google.pubsub.v1.Schema", HTTP: []Binding{{"GET", "/v1/{name=projects/*/schemas/*}", ""}}},
		{Name: "ListSchemas", Input: "google.pubsub.v1.ListSchemasRequest", Output: "google.pubsub.v1.ListSchemasResponse", HTTP: []Binding{{"GET", "/v1/{parent=projects/*}/schemas", ""}}},
		{Name: "ListSchemaRevisions", Input: "google.pubsub.v1.ListSchemaRevisionsRequest", Output: "google.pubsub.v1.ListSchemaRevisionsResponse", HTTP: []Binding{{"GET", "/v1/{name=projects/*/schemas/*}:listRevisions", ""}}},
		{Name: "CommitSchema", Input: "google.pubsub.v1.CommitSchemaRequest", Output: "google.pubsub.v1.Schema", HTTP: []Binding{{"POST", "/v1/{name=projects/*/schemas/*}:commit", "*"}}},
		{Name: "RollbackSchema", Input: "google.pubsub.v1.RollbackSchemaRequest", Output: "google.pubsub.v1.Schema", HTTP: []Binding{{"POST", "/v1/{name=projects/*/schemas/*}:rollback", "*"}}},
		{Name: "DeleteSchemaRevision", Input: "google.pubsub.v1.DeleteSchemaRevisionRequest", Output: "google.pubsub.v1.Schema", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/schemas/*}:deleteRevision", ""}}},
		{Name: "DeleteSchema", Input: "google.pubsub.v1.DeleteSchemaRequest", Output: "google.protobuf.Empty", HTTP: []Binding{{"DELETE", "/v1/{name=projects/*/schemas/*}", ""}}},
		{Name: "ValidateSchema", Input: "google.pubsub.v1.ValidateSchemaRequest", Output: "google.pubsub.v1.ValidateSchemaResponse", HTTP: []Binding{{"POST", "/v1/{parent=projects/*}/schemas:validate", "*"}}},
		{Name: "ValidateMessage", Input: "google.pubsub.v1.ValidateMessageRequest", Output: "google.pubsub.v1.ValidateMessageResponse", HTTP: []Binding{{"POST", "/v1/{parent=projects/*}/schemas:validateMessage", "*"}}},
	}},
}

var protoFields = map[string]map[string]Behavior{
	"google.cloud.certificatemanager.v1.Certificate": {
		"create_time":     OutputOnly,
		"update_time":     OutputOnly,
		"san_dnsnames":    OutputOnly,
		"pem_certificate": OutputOnly,
		"expire_time":     OutputOnly,
		"scope":           Immutable,
	},
	"google.cloud.certificatemanager.v1.Certificate.ManagedCertificate": {
		"domains":                    Immutable,
		"dns_authorizations":         Immutable,
		"issuance_config":            Immutable,
		"state":                      OutputOnly,
		"provisioning_issue":         OutputOnly,
		"authorization_attempt_info": OutputOnly,
	},
	"google.cloud.certificatemanager.v1.Certificate.ManagedCertificate.AuthorizationAttemptInfo": {
		"state":          OutputOnly,
		"failure_reason": OutputOnly,
		"details":        OutputOnly,
	},
	"google.cloud.certificatemanager.v1.Certificate.ManagedCertificate.ProvisioningIssue": {
		"reason":  OutputOnly,
		"details": OutputOnly,
	},
	"google.cloud.certificatemanager.v1.Certificate.SelfManagedCertificate": {
		"pem_certificate": InputOnly,
		"pem_private_key": InputOnly,
	},
	"google.cloud.certificatemanager.v1.CertificateIssuanceConfig": {
		"create_time":                  OutputOnly,
		"update_time":                  OutputOnly,
		"certificate_authority_config": Required,
		"lifetime":                     Required,
		"rotation_window_percentage":   Required,
		"key_algorithm":                Required,
	},
	"google.cloud.certificatemanager.v1.CertificateIssuanceConfig.CertificateAuthorityConfig.CertificateAuthorityServiceConfig": {
		"ca_pool": Required,
	},
	"google.cloud.certificatemanager.v1.CertificateMap": {
		"create_time":  OutputOnly,
		"update_time":  OutputOnly,
		"gclb_targets": OutputOnly,
	},
	"google.cloud.certificatemanager.v1.CertificateMap.GclbTarget": {
		"target_https_proxy": OutputOnly,
		"target_ssl_proxy":   OutputOnly,
		"ip_configs":         OutputOnly,
	},
	"google.cloud.certificatemanager.v1.CertificateMap.GclbTarget.IpConfig": {
		"ip_address": OutputOnly,
		"ports":      OutputOnly,
	},
	"google.cloud.certificatemanager.v1.CertificateMapEntry": {
		"create_time": OutputOnly,
		"update_time": OutputOnly,
		"state":       OutputOnly,
	},
	"google.cloud.certificatemanager.v1.CreateCertificateIssuanceConfigRequest": {
		"parent":                         Required,
		"certificate_issuance_config_id": Required,
		"certificate_issuance_config":    Required,
	},
	"google.cloud.certificatemanager.v1.CreateCertificateMapEntryRequest": {
		"parent":                   Required,
		"certificate_map_entry_id": Required,
		"certificate_map_entry":    Required,
	},
	"google.cloud.certificatemanager.v1.CreateCertificateMapRequest": {
		"parent":             Required,
		"certificate_map_id": Required,
		"certificate_map":    Required,
	},
	"google.cloud.certificatemanager.v1.CreateCertificateRequest": {
		"parent":         Required,
		"certificate_id": Required,
		"certificate":    Required,
	},
	"google.cloud.certificatemanager.v1.CreateDnsAuthorizationRequest": {
		"parent":               Required,
		"dns_authorization_id": Required,
		"dns_authorization":    Required,
	},
	"google.cloud.certificatemanager.v1.CreateTrustConfigRequest": {
		"parent":          Required,
		"trust_config_id": Required,
		"trust_config":    Required,
	},
	"google.cloud.certificatemanager.v1.DeleteCertificateIssuanceConfigRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.DeleteCertificateMapEntryRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.DeleteCertificateMapRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.DeleteCertificateRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.DeleteDnsAuthorizationRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.DeleteTrustConfigRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.DnsAuthorization": {
		"create_time":         OutputOnly,
		"update_time":         OutputOnly,
		"domain":              Required | Immutable,
		"dns_resource_record": OutputOnly,
		"type":                Immutable,
	},
	"google.cloud.certificatemanager.v1.DnsAuthorization.DnsResourceRecord": {
		"name": OutputOnly,
		"type": OutputOnly,
		"data": OutputOnly,
	},
	"google.cloud.certificatemanager.v1.GetCertificateIssuanceConfigRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.GetCertificateMapEntryRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.GetCertificateMapRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.GetCertificateRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.GetDnsAuthorizationRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.GetTrustConfigRequest": {
		"name": Required,
	},
	"google.cloud.certificatemanager.v1.ListCertificateIssuanceConfigsRequest": {
		"parent": Required,
	},
	"google.cloud.certificatemanager.v1.ListCertificateMapEntriesRequest": {
		"parent": Required,
	},
	"google.cloud.certificatemanager.v1.ListCertificateMapsRequest": {
		"parent": Required,
	},
	"google.cloud.certificatemanager.v1.ListCertificatesRequest": {
		"parent": Required,
	},
	"google.cloud.certificatemanager.v1.ListDnsAuthorizationsRequest": {
		"parent": Required,
	},
	"google.cloud.certificatemanager.v1.ListTrustConfigsRequest": {
		"parent": Required,
	},
	"google.cloud.certificatemanager.v1.TrustConfig": {
		"create_time": OutputOnly,
		"update_time": OutputOnly,
	},
	"google.cloud.certificatemanager.v1.UpdateCertificateMapEntryRequest": {
		"certificate_map_entry": Required,
		"update_mask":           Required,
	},
	"google.cloud.certificatemanager.v1.UpdateCertificateMapRequest": {
		"certificate_map": Required,
		"update_mask":     Required,
	},
	"google.cloud.certificatemanager.v1.UpdateCertificateRequest": {
		"certificate": Required,
		"update_mask": Required,
	},
	"google.cloud.certificatemanager.v1.UpdateDnsAuthorizationRequest": {
		"dns_authorization": Required,
		"update_mask":       Required,
	},
	"google.cloud.certificatemanager.v1.UpdateTrustConfigRequest": {
		"trust_config": Required,
		"update_mask":  Required,
	},
	"google.cloud.networksecurity.v1.AuthorizationPolicy": {
		"name":        Required,
		"description": Optional,
		"create_time": OutputOnly,
		"update_time": OutputOnly,
		"labels":      Optional,
		"action":      Required,
		"rules":       Optional,
	},
	"google.cloud.networksecurity.v1.AuthorizationPolicy.Rule": {
		"sources":      Optional,
		"destinations": Optional,
	},
	"google.cloud.networksecurity.v1.AuthorizationPolicy.Rule.Destination": {
		"hosts":             Required,
		"ports":             Required,
		"methods":           Optional,
		"http_header_match": Optional,
	},
	"google.cloud.networksecurity.v1.AuthorizationPolicy.Rule.Destination.HttpHeaderMatch": {
		"regex_match": Required,
		"header_name": Required,
	},
	"google.cloud.networksecurity.v1.AuthorizationPolicy.Rule.Source": {
		"principals": Optional,
		"ip_blocks":  Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy": {
		"name":            Required | Identifier,
		"create_time":     OutputOnly,
		"update_time":     OutputOnly,
		"description":     Optional,
		"labels":          Optional,
		"target":          Required,
		"http_rules":      Optional,
		"network_rules":   Optional,
		"action":          Required,
		"custom_provider": Optional,
		"policy_profile":  Optional | Immutable,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule": {
		"from": Optional,
		"to":   Optional,
		"when": Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.From": {
		"sources":     Optional,
		"not_sources": Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.From.RequestSource": {
		"principals": Optional,
		"ip_blocks":  Optional,
		"resources":  Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.HeaderMatch": {
		"name":  Optional,
		"value": Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.IpBlock": {
		"prefix": Required,
		"length": Required,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.Principal": {
		"principal_selector": Optional,
		"principal":          Required,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.RequestResource": {
		"tag_value_id_set":    Optional,
		"iam_service_account": Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.RequestResource.TagValueIdSet": {
		"ids": Required,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.To": {
		"operations":     Optional,
		"not_operations": Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.To.RequestOperation": {
		"header_set": Optional,
		"hosts":      Optional,
		"paths":      Optional,
		"methods":    Optional,
		"mcp":        Optional,
		"snis":       Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.To.RequestOperation.HeaderSet": {
		"headers": Required,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.To.RequestOperation.MCP": {
		"base_protocol_methods_option": Optional,
		"methods":                      Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.AuthzRule.To.RequestOperation.MCPMethod": {
		"name":   Required,
		"params": Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.CustomProvider": {
		"cloud_iap":       Optional,
		"authz_extension": Optional,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.CustomProvider.AuthzExtension": {
		"resources": Required,
	},
	"google.cloud.networksecurity.v1.AuthzPolicy.Target": {
		"load_balancing_scheme": Optional,
		"resources":             Required,
	},
	"google.cloud.networksecurity.v1.BackendAuthenticationConfig": {
		"name":               Required,
		"description":        Optional,
		"create_time":        OutputOnly,
		"update_time":        OutputOnly,
		"client_certificate": Optional,
		"trust_config":       Optional,
		"etag":               OutputOnly,
	},
	"google.cloud.networksecurity.v1.CertificateProviderInstance": {
		"plugin_instance": Required,
	},
	"google.cloud.networksecurity.v1.ClientTlsPolicy": {
		"name":                 Required,
		"description":          Optional,
		"create_time":          OutputOnly,
		"update_time":          OutputOnly,
		"labels":               Optional,
		"sni":                  Optional,
		"client_certificate":   Optional,
		"server_validation_ca": Optional,
	},
	"google.cloud.networksecurity.v1.CreateAuthorizationPolicyRequest": {
		"parent":                  Required,
		"authorization_policy_id": Required,
		"authorization_policy":    Required,
	},
	"google.cloud.networksecurity.v1.CreateAuthzPolicyRequest": {
		"parent":          Required,
		"authz_policy_id": Required,
		"authz_policy":    Required,
		"request_id":      Optional,
	},
	"google.cloud.networksecurity.v1.CreateBackendAuthenticationConfigRequest": {
		"parent":                           Required,
		"backend_authentication_config_id": Required,
		"backend_authentication_config":    Required,
	},
	"google.cloud.networksecurity.v1.CreateClientTlsPolicyRequest": {
		"parent":               Required,
		"client_tls_policy_id": Required,
		"client_tls_policy":    Required,
	},
	"google.cloud.networksecurity.v1.CreateGatewaySecurityPolicyRequest": {
		"parent":                     Required,
		"gateway_security_policy_id": Required,
		"gateway_security_policy":    Required,
	},
	"google.cloud.networksecurity.v1.CreateGatewaySecurityPolicyRuleRequest": {
		"parent":                       Required,
		"gateway_security_policy_rule": Required,
	},
	"google.cloud.networksecurity.v1.CreateServerTlsPolicyRequest": {
		"parent":               Required,
		"server_tls_policy_id": Required,
		"server_tls_policy":    Required,
	},
	"google.cloud.networksecurity.v1.CreateTlsInspectionPolicyRequest": {
		"parent":                   Required,
		"tls_inspection_policy_id": Required,
		"tls_inspection_policy":    Required,
	},
	"google.cloud.networksecurity.v1.CreateUrlListRequest": {
		"parent":      Required,
		"url_list_id": Required,
		"url_list":    Required,
	},
	"google.cloud.networksecurity.v1.DeleteAuthorizationPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.DeleteAuthzPolicyRequest": {
		"name":       Required,
		"request_id": Optional,
	},
	"google.cloud.networksecurity.v1.DeleteBackendAuthenticationConfigRequest": {
		"name": Required,
		"etag": Optional,
	},
	"google.cloud.networksecurity.v1.DeleteClientTlsPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.DeleteGatewaySecurityPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.DeleteGatewaySecurityPolicyRuleRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.DeleteServerTlsPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.DeleteTlsInspectionPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.DeleteUrlListRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.GatewaySecurityPolicy": {
		"name":                  Required,
		"create_time":           OutputOnly,
		"update_time":           OutputOnly,
		"description":           Optional,
		"tls_inspection_policy": Optional,
	},
	"google.cloud.networksecurity.v1.GatewaySecurityPolicyRule": {
		"basic_profile":          Required,
		"name":                   Required | Immutable,
		"create_time":            OutputOnly,
		"update_time":            OutputOnly,
		"enabled":                Required,
		"priority":               Required,
		"description":            Optional,
		"session_matcher":        Required,
		"application_matcher":    Optional,
		"tls_inspection_enabled": Optional,
	},
	"google.cloud.networksecurity.v1.GetAuthorizationPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.GetAuthzPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.GetBackendAuthenticationConfigRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.GetClientTlsPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.GetGatewaySecurityPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.GetGatewaySecurityPolicyRuleRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.GetServerTlsPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.GetTlsInspectionPolicyRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.GetUrlListRequest": {
		"name": Required,
	},
	"google.cloud.networksecurity.v1.GrpcEndpoint": {
		"target_uri": Required,
	},
	"google.cloud.networksecurity.v1.ListAuthorizationPoliciesRequest": {
		"parent": Required,
	},
	"google.cloud.networksecurity.v1.ListAuthzPoliciesRequest": {
		"parent":     Required,
		"page_size":  Optional,
		"page_token": Optional,
		"filter":     Optional,
		"order_by":   Optional,
	},
	"google.cloud.networksecurity.v1.ListBackendAuthenticationConfigsRequest": {
		"parent": Required,
	},
	"google.cloud.networksecurity.v1.ListClientTlsPoliciesRequest": {
		"parent": Required,
	},
	"google.cloud.networksecurity.v1.ListGatewaySecurityPoliciesRequest": {
		"parent": Required,
	},
	"google.cloud.networksecurity.v1.ListGatewaySecurityPolicyRulesRequest": {
		"parent": Required,
	},
	"google.cloud.networksecurity.v1.ListServerTlsPoliciesRequest": {
		"parent":                 Required,
		"return_partial_success": Optional,
	},
	"google.cloud.networksecurity.v1.ListTlsInspectionPoliciesRequest": {
		"parent": Required,
	},
	"google.cloud.networksecurity.v1.ListUrlListsRequest": {
		"parent": Required,
	},
	"google.cloud.networksecurity.v1.ServerTlsPolicy": {
		"name":        Required,
		"create_time": OutputOnly,
		"update_time": OutputOnly,
	},
	"google.cloud.networksecurity.v1.TlsInspectionPolicy": {
		"name":                  Required,
		"description":           Optional,
		"create_time":           OutputOnly,
		"update_time":           OutputOnly,
		"ca_pool":               Required,
		"trust_config":          Optional,
		"exclude_public_ca_set": Optional,
		"min_tls_version":       Optional,
		"tls_feature_profile":   Optional,
		"custom_tls_features":   Optional,
	},
	"google.cloud.networksecurity.v1.UpdateAuthorizationPolicyRequest": {
		"update_mask":          Optional,
		"authorization_policy": Required,
	},
	"google.cloud.networksecurity.v1.UpdateAuthzPolicyRequest": {
		"update_mask":  Required,
		"authz_policy": Required,
		"request_id":   Optional,
	},
	"google.cloud.networksecurity.v1.UpdateBackendAuthenticationConfigRequest": {
		"update_mask":                   Optional,
		"backend_authentication_config": Required,
	},
	"google.cloud.networksecurity.v1.UpdateClientTlsPolicyRequest": {
		"update_mask":       Optional,
		"client_tls_policy": Required,
	},
	"google.cloud.networksecurity.v1.UpdateGatewaySecurityPolicyRequest": {
		"update_mask":             Optional,
		"gateway_security_policy": Required,
	},
	"google.cloud.networksecurity.v1.UpdateGatewaySecurityPolicyRuleRequest": {
		"update_mask":                  Optional,
		"gateway_security_policy_rule": Required,
	},
	"google.cloud.networksecurity.v1.UpdateServerTlsPolicyRequest": {
		"update_mask":       Optional,
		"server_tls_policy": Required,
	},
	"google.cloud.networksecurity.v1.UpdateTlsInspectionPolicyRequest": {
		"update_mask":           Optional,
		"tls_inspection_policy": Required,
	},
	"google.cloud.networksecurity.v1.UpdateUrlListRequest": {
		"update_mask": Optional,
		"url_list":    Required,
	},
	"google.cloud.networksecurity.v1.UrlList": {
		"name":        Required,
		"create_time": OutputOnly,
		"update_time": OutputOnly,
		"description": Optional,
		"values":      Required,
	},
	"google.container.v1.AdditionalPodRangesConfig": {
		"pod_range_info": OutputOnly,
	},
	"google.container.v1.AddonsConfig": {
		"stateful_ha_config":      Optional,
		"ray_operator_config":     Optional,
		"pod_snapshot_config":     Optional,
		"slice_controller_config": Optional,
		"agent_sandbox_config":    Optional,
		"node_readiness_config":   Optional,
	},
	"google.container.v1.AgentSandboxConfig": {
		"enabled": Optional,
	},
	"google.container.v1.AutoUpgradeOptions": {
		"auto_upgrade_start_time": OutputOnly,
		"description":             OutputOnly,
	},
	"google.container.v1.BlueGreenSettings.AutoscaledRolloutPolicy": {
		"wait_for_drain_duration": Optional,
	},
	"google.container.v1.Cluster": {
		"self_link":                 OutputOnly,
		"zone":                      OutputOnly,
		"endpoint":                  OutputOnly,
		"current_master_version":    OutputOnly,
		"current_emulated_version":  OutputOnly,
		"rollback_safe_upgrade":     Optional,
		"current_node_version":      OutputOnly,
		"create_time":               OutputOnly,
		"status":                    OutputOnly,
		"status_message":            OutputOnly,
		"node_ipv4_cidr_size":       OutputOnly,
		"services_ipv4_cidr":        OutputOnly,
		"instance_group_urls":       OutputOnly,
		"current_node_count":        OutputOnly,
		"expire_time":               OutputOnly,
		"location":                  OutputOnly,
		"tpu_ipv4_cidr_block":       OutputOnly,
		"id":                        OutputOnly,
		"security_posture_config":   Optional,
		"compliance_posture_config": Optional,
		"satisfies_pzs":             OutputOnly,
		"satisfies_pzi":             OutputOnly,
		"schedule_upgrade_config":   Optional,
		"node_creation_config":      Optional,
	},
	"google.container.v1.ClusterUpdate": {
		"desired_rollback_safe_upgrade": Optional,
		"desired_node_creation_config":  Optional,
		"desired_emulated_version":      Optional,
	},
	"google.container.v1.CompleteControlPlaneUpgradeRequest": {
		"name":    Required,
		"version": Optional,
	},
	"google.container.v1.ContainerdConfig": {
		"writable_cgroups": Optional,
	},
	"google.container.v1.ContainerdConfig.WritableCgroups": {
		"enabled": Optional,
	},
	"google.container.v1.ControlPlaneEndpointsConfig.DNSEndpointConfig": {
		"endpoint": OutputOnly,
	},
	"google.container.v1.ControlPlaneEndpointsConfig.IPEndpointsConfig": {
		"public_endpoint":  OutputOnly,
		"private_endpoint": OutputOnly,
	},
	"google.container.v1.CreateClusterRequest": {
		"cluster": Required,
	},
	"google.container.v1.CreateNodePoolRequest": {
		"node_pool": Required,
	},
	"google.container.v1.DNSConfig": {
		"additive_vpc_scope_dns_domain": Optional,
	},
	"google.container.v1.DailyMaintenanceWindow": {
		"duration": OutputOnly,
	},
	"google.container.v1.DatabaseEncryption": {
		"current_state":         OutputOnly,
		"decryption_keys":       OutputOnly,
		"last_operation_errors": OutputOnly,
	},
	"google.container.v1.DataplaneV2Config": {
		"scalability_mode": Optional,
	},
	"google.container.v1.DiskIoScheduler": {
		"node_system_io_scheduler":        Optional,
		"node_attached_disk_io_scheduler": Optional,
	},
	"google.container.v1.DisruptionBudget": {
		"minor_version_disruption_interval":  Optional,
		"patch_version_disruption_interval":  Optional,
		"last_minor_version_disruption_time": OutputOnly,
		"last_disruption_time":               OutputOnly,
	},
	"google.container.v1.EnterpriseConfig": {
		"cluster_tier": OutputOnly,
	},
	"google.container.v1.EvictionGracePeriod": {
		"memory_available":    Optional,
		"nodefs_available":    Optional,
		"nodefs_inodes_free":  Optional,
		"imagefs_available":   Optional,
		"imagefs_inodes_free": Optional,
		"pid_available":       Optional,
	},
	"google.container.v1.EvictionMinimumReclaim": {
		"memory_available":    Optional,
		"nodefs_available":    Optional,
		"nodefs_inodes_free":  Optional,
		"imagefs_available":   Optional,
		"imagefs_inodes_free": Optional,
		"pid_available":       Optional,
	},
	"google.container.v1.EvictionSignals": {
		"memory_available":    Optional,
		"nodefs_available":    Optional,
		"nodefs_inodes_free":  Optional,
		"imagefs_available":   Optional,
		"imagefs_inodes_free": Optional,
		"pid_available":       Optional,
	},
	"google.container.v1.FetchClusterUpgradeInfoRequest": {
		"name": Required,
	},
	"google.container.v1.FetchNodePoolUpgradeInfoRequest": {
		"name": Required,
	},
	"google.container.v1.Fleet": {
		"membership":     OutputOnly,
		"pre_registered": OutputOnly,
	},
	"google.container.v1.IPAllocationPolicy": {
		"subnet_ipv6_cidr_block":             OutputOnly,
		"services_ipv6_cidr_block":           OutputOnly,
		"additional_pod_ranges_config":       OutputOnly,
		"default_pod_ipv4_range_utilization": OutputOnly,
		"additional_ip_ranges_configs":       OutputOnly,
		"auto_ipam_config":                   Optional,
	},
	"google.container.v1.LinuxNodeConfig": {
		"hugepages":                    Optional,
		"transparent_hugepage_enabled": Optional,
		"transparent_hugepage_defrag":  Optional,
		"custom_node_init":             Optional,
		"swap_config":                  Optional,
		"node_kernel_module_loading":   Optional,
		"accurate_time_config":         Optional,
		"node_vfio_config":             Optional,
		"disk_io_scheduler":            Optional,
	},
	"google.container.v1.LinuxNodeConfig.CustomNodeInit": {
		"init_script": Optional,
	},
	"google.container.v1.LinuxNodeConfig.CustomNodeInit.InitScript": {
		"args": Optional,
	},
	"google.container.v1.LinuxNodeConfig.HugepagesConfig": {
		"hugepage_size2m": Optional,
		"hugepage_size1g": Optional,
	},
	"google.container.v1.LinuxNodeConfig.NodeVfioConfig": {
		"dma_entry_limit": Optional,
	},
	"google.container.v1.LinuxNodeConfig.SwapConfig": {
		"enabled":           Optional,
		"encryption_config": Optional,
	},
	"google.container.v1.LinuxNodeConfig.SwapConfig.EncryptionConfig": {
		"disabled": Optional,
	},
	"google.container.v1.MaintenancePolicy": {
		"disruption_budget": Optional,
	},
	"google.container.v1.MasterAuth": {
		"cluster_ca_certificate": OutputOnly,
		"client_certificate":     OutputOnly,
		"client_key":             OutputOnly,
	},
	"google.container.v1.NetworkConfig": {
		"network":             OutputOnly,
		"subnetwork":          OutputOnly,
		"dataplane_v2_config": Optional,
	},
	"google.container.v1.NodeConfig": {
		"enable_confidential_storage": Optional,
		"effective_cgroup_mode":       OutputOnly,
		"taint_config":                Optional,
	},
	"google.container.v1.NodeKubeletConfig": {
		"topology_manager":                            Optional,
		"memory_manager":                              Optional,
		"image_gc_low_threshold_percent":              Optional,
		"image_gc_high_threshold_percent":             Optional,
		"image_minimum_gc_age":                        Optional,
		"image_maximum_gc_age":                        Optional,
		"container_log_max_size":                      Optional,
		"container_log_max_files":                     Optional,
		"allowed_unsafe_sysctls":                      Optional,
		"eviction_soft":                               Optional,
		"eviction_soft_grace_period":                  Optional,
		"eviction_minimum_reclaim":                    Optional,
		"eviction_max_pod_grace_period_seconds":       Optional,
		"max_parallel_image_pulls":                    Optional,
		"single_process_oom_kill":                     Optional,
		"crash_loop_back_off":                         Optional,
		"shutdown_grace_period_seconds":               Optional,
		"shutdown_grace_period_critical_pods_seconds": Optional,
	},
	"google.container.v1.NodeKubeletConfig.CrashLoopBackOffConfig": {
		"max_container_restart_period": Optional,
	},
	"google.container.v1.NodeNetworkConfig": {
		"create_pod_range":            InputOnly,
		"pod_ipv4_range_utilization":  OutputOnly,
		"subnetwork":                  Optional,
		"network_tier_config":         OutputOnly,
		"accelerator_network_profile": Immutable,
	},
	"google.container.v1.NodePool": {
		"self_link":           OutputOnly,
		"instance_group_urls": OutputOnly,
		"status":              OutputOnly,
		"status_message":      OutputOnly,
		"conditions":          OutputOnly,
		"pod_ipv4_cidr_size":  OutputOnly,
		"update_info":         OutputOnly,
		"etag":                OutputOnly,
		"maintenance_policy":  Optional,
		"kubelet_cert_info":   OutputOnly,
	},
	"google.container.v1.NodePool.ExclusionUntilEndOfSupport": {
		"enabled":    Optional,
		"start_time": OutputOnly,
		"end_time":   OutputOnly,
	},
	"google.container.v1.NodePool.KubeletCertInfo": {
		"tpm_bootstrap_cert_expire_time":     OutputOnly,
		"non_tpm_bootstrap_cert_expire_time": OutputOnly,
	},
	"google.container.v1.NodePool.NodePoolMaintenancePolicy": {
		"exclusion_until_end_of_support": Optional,
	},
	"google.container.v1.NodePool.PlacementPolicy": {
		"tpu_topology": Optional,
	},
	"google.container.v1.NodePoolAutoConfig": {
		"linux_node_config": OutputOnly,
	},
	"google.container.v1.NodeReadinessConfig": {
		"enabled": Optional,
	},
	"google.container.v1.PrivateClusterConfig": {
		"private_endpoint": OutputOnly,
		"public_endpoint":  OutputOnly,
		"peering_name":     OutputOnly,
	},
	"google.container.v1.RangeInfo": {
		"range_name":  OutputOnly,
		"utilization": OutputOnly,
	},
	"google.container.v1.RayOperatorConfig": {
		"ray_cluster_logging_config":    Optional,
		"ray_cluster_monitoring_config": Optional,
	},
	"google.container.v1.RecurringMaintenanceWindow": {
		"delay_until":       Optional,
		"window_start_time": Required,
		"window_duration":   Required,
		"recurrence":        Required,
	},
	"google.container.v1.RollbackSafeUpgrade": {
		"control_plane_soak_duration": Optional,
	},
	"google.container.v1.ScheduleUpgradeConfig": {
		"enabled": Optional,
	},
	"google.container.v1.SetAddonsConfigRequest": {
		"addons_config": Required,
	},
	"google.container.v1.SetLabelsRequest": {
		"resource_labels":   Required,
		"label_fingerprint": Required,
	},
	"google.container.v1.SetLegacyAbacRequest": {
		"enabled": Required,
	},
	"google.container.v1.SetLocationsRequest": {
		"locations": Required,
	},
	"google.container.v1.SetLoggingServiceRequest": {
		"logging_service": Required,
	},
	"google.container.v1.SetMaintenancePolicyRequest": {
		"project_id":         Required,
		"zone":               Required,
		"cluster_id":         Required,
		"maintenance_policy": Required,
	},
	"google.container.v1.SetMasterAuthRequest": {
		"action": Required,
		"update": Required,
	},
	"google.container.v1.SetMonitoringServiceRequest": {
		"monitoring_service": Required,
	},
	"google.container.v1.SetNetworkPolicyRequest": {
		"network_policy": Required,
	},
	"google.container.v1.SetNodePoolAutoscalingRequest": {
		"autoscaling": Required,
	},
	"google.container.v1.SetNodePoolManagementRequest": {
		"management": Required,
	},
	"google.container.v1.SetNodePoolSizeRequest": {
		"node_count": Required,
	},
	"google.container.v1.SliceControllerConfig": {
		"enabled": Optional,
	},
	"google.container.v1.SoleTenantConfig": {
		"min_node_cpus": Optional,
	},
	"google.container.v1.TaintConfig": {
		"architecture_taint_behavior": Optional,
	},
	"google.container.v1.UpdateClusterRequest": {
		"update": Required,
	},
	"google.container.v1.UpdateMasterRequest": {
		"master_version": Required,
	},
	"google.container.v1.UpdateNodePoolRequest": {
		"machine_type":       Optional,
		"disk_type":          Optional,
		"disk_size_gb":       Optional,
		"maintenance_policy": Optional,
	},
	"google.container.v1.UserManagedKeysConfig": {
		"control_plane_disk_encryption_key_versions": OutputOnly,
	},
	"google.devtools.artifactregistry.v1.Attachment": {
		"target":           Required,
		"annotations":      Optional,
		"create_time":      OutputOnly,
		"update_time":      OutputOnly,
		"files":            Required,
		"oci_version_name": OutputOnly,
	},
	"google.devtools.artifactregistry.v1.BatchDeleteVersionsRequest": {
		"names": Required,
	},
	"google.devtools.artifactregistry.v1.CreateAttachmentRequest": {
		"parent":        Required,
		"attachment_id": Required,
		"attachment":    Required,
	},
	"google.devtools.artifactregistry.v1.CreateRepositoryRequest": {
		"parent":        Required,
		"repository_id": Required,
		"repository":    Required,
	},
	"google.devtools.artifactregistry.v1.CreateRuleRequest": {
		"parent": Required,
	},
	"google.devtools.artifactregistry.v1.DeleteAttachmentRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.DeleteFileRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.DeletePackageRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.DeleteRepositoryRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.DeleteRuleRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.ExportArtifactRequest": {
		"repository": Required,
	},
	"google.devtools.artifactregistry.v1.File": {
		"create_time": OutputOnly,
		"update_time": OutputOnly,
		"fetch_time":  OutputOnly,
		"annotations": Optional,
	},
	"google.devtools.artifactregistry.v1.GetAttachmentRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.GetDockerImageRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.GetFileRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.GetMavenArtifactRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.GetNpmPackageRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.GetPackageRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.GetProjectSettingsRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.GetPythonPackageRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.GetRepositoryRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.GetRuleRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.GetVPCSCConfigRequest": {
		"name": Required,
	},
	"google.devtools.artifactregistry.v1.ListAttachmentsRequest": {
		"parent": Required,
		"filter": Optional,
	},
	"google.devtools.artifactregistry.v1.ListDockerImagesRequest": {
		"parent": Required,
	},
	"google.devtools.artifactregistry.v1.ListFilesRequest": {
		"parent": Required,
	},
	"google.devtools.artifactregistry.v1.ListMavenArtifactsRequest": {
		"parent": Required,
	},
	"google.devtools.artifactregistry.v1.ListNpmPackagesRequest": {
		"parent": Required,
	},
	"google.devtools.artifactregistry.v1.ListPackagesRequest": {
		"parent":   Required,
		"filter":   Optional,
		"order_by": Optional,
	},
	"google.devtools.artifactregistry.v1.ListPythonPackagesRequest": {
		"parent": Required,
	},
	"google.devtools.artifactregistry.v1.ListRepositoriesRequest": {
		"parent":   Required,
		"filter":   Optional,
		"order_by": Optional,
	},
	"google.devtools.artifactregistry.v1.ListRulesRequest": {
		"parent": Required,
	},
	"google.devtools.artifactregistry.v1.ListVersionsRequest": {
		"order_by": Optional,
		"filter":   Optional,
	},
	"google.devtools.artifactregistry.v1.Package": {
		"annotations": Optional,
	},
	"google.devtools.artifactregistry.v1.RemoteRepositoryConfig": {
		"upstream_credentials":        Optional,
		"disable_upstream_validation": InputOnly,
	},
	"google.devtools.artifactregistry.v1.RemoteRepositoryConfig.CommonRemoteRepository": {
		"uri": Required,
	},
	"google.devtools.artifactregistry.v1.Repository": {
		"format":                        Optional,
		"create_time":                   OutputOnly,
		"update_time":                   OutputOnly,
		"mode":                          Optional,
		"cleanup_policies":              Optional,
		"size_bytes":                    OutputOnly,
		"satisfies_pzs":                 OutputOnly,
		"cleanup_policy_dry_run":        Optional,
		"vulnerability_scanning_config": Optional,
		"disallow_unspecified_mode":     Optional,
		"satisfies_pzi":                 OutputOnly,
		"registry_uri":                  OutputOnly,
	},
	"google.devtools.artifactregistry.v1.Repository.VulnerabilityScanningConfig": {
		"enablement_config":       Optional,
		"last_enable_time":        OutputOnly,
		"enablement_state":        OutputOnly,
		"enablement_state_reason": OutputOnly,
	},
	"google.devtools.artifactregistry.v1.Rule": {
		"condition": Optional,
	},
	"google.devtools.artifactregistry.v1.UpdateFileRequest": {
		"file":        Required,
		"update_mask": Required,
	},
	"google.devtools.artifactregistry.v1.UpdateVersionRequest": {
		"version": Required,
	},
	"google.devtools.artifactregistry.v1.Version": {
		"metadata":     OutputOnly,
		"annotations":  Optional,
		"fingerprints": OutputOnly,
	},
	"google.iam.credentials.v1.GenerateAccessTokenRequest": {
		"name":  Required,
		"scope": Required,
	},
	"google.iam.credentials.v1.GenerateIdTokenRequest": {
		"name":     Required,
		"audience": Required,
	},
	"google.iam.credentials.v1.SignBlobRequest": {
		"name":    Required,
		"payload": Required,
	},
	"google.iam.credentials.v1.SignJwtRequest": {
		"name":    Required,
		"payload": Required,
	},
	"google.iam.v1.GetIamPolicyRequest": {
		"resource": Required,
	},
	"google.iam.v1.SetIamPolicyRequest": {
		"resource": Required,
		"policy":   Required,
	},
	"google.iam.v1.TestIamPermissionsRequest": {
		"resource":    Required,
		"permissions": Required,
	},
	"google.pubsub.v1.AIInference": {
		"endpoint":               Required,
		"unstructured_inference": Optional,
		"service_account_email":  Optional,
	},
	"google.pubsub.v1.AIInference.UnstructuredInference": {
		"parameters": Optional,
	},
	"google.pubsub.v1.AcknowledgeRequest": {
		"subscription": Required,
		"ack_ids":      Required,
	},
	"google.pubsub.v1.BigQueryConfig": {
		"table":                 Optional,
		"use_topic_schema":      Optional,
		"write_metadata":        Optional,
		"drop_unknown_fields":   Optional,
		"state":                 OutputOnly,
		"use_table_schema":      Optional,
		"service_account_email": Optional,
	},
	"google.pubsub.v1.BigtableConfig": {
		"table":                 Optional,
		"app_profile_id":        Optional,
		"service_account_email": Optional,
		"write_metadata":        Optional,
		"state":                 OutputOnly,
	},
	"google.pubsub.v1.CloudStorageConfig": {
		"bucket":                   Required,
		"filename_prefix":          Optional,
		"filename_suffix":          Optional,
		"filename_datetime_format": Optional,
		"text_config":              Optional,
		"avro_config":              Optional,
		"max_duration":             Optional,
		"max_bytes":                Optional,
		"max_messages":             Optional,
		"state":                    OutputOnly,
		"service_account_email":    Optional,
	},
	"google.pubsub.v1.CloudStorageConfig.AvroConfig": {
		"write_metadata":   Optional,
		"use_topic_schema": Optional,
	},
	"google.pubsub.v1.CommitSchemaRequest": {
		"name":   Required,
		"schema": Required,
	},
	"google.pubsub.v1.CompiledProtoSchema": {
		"root_message":   Required,
		"compiled_bytes": Required,
	},
	"google.pubsub.v1.Compression": {
		"compression_algorithm": Required,
		"compression_mode":      Required,
	},
	"google.pubsub.v1.CreateSchemaRequest": {
		"parent": Required,
		"schema": Required,
	},
	"google.pubsub.v1.CreateSnapshotRequest": {
		"name":         Required,
		"subscription": Required,
		"labels":       Optional,
		"tags":         InputOnly | Immutable | Optional,
	},
	"google.pubsub.v1.DeadLetterPolicy": {
		"dead_letter_topic":     Optional,
		"max_delivery_attempts": Optional,
	},
	"google.pubsub.v1.DeleteSchemaRequest": {
		"name": Required,
	},
	"google.pubsub.v1.DeleteSchemaRevisionRequest": {
		"name":        Required,
		"revision_id": Optional,
	},
	"google.pubsub.v1.DeleteSnapshotRequest": {
		"snapshot": Required,
	},
	"google.pubsub.v1.DeleteSubscriptionRequest": {
		"subscription": Required,
	},
	"google.pubsub.v1.DeleteTopicRequest": {
		"topic": Required,
	},
	"google.pubsub.v1.DetachSubscriptionRequest": {
		"subscription": Required,
	},
	"google.pubsub.v1.ExpirationPolicy": {
		"ttl": Optional,
	},
	"google.pubsub.v1.GetSchemaRequest": {
		"name": Required,
	},
	"google.pubsub.v1.GetSnapshotRequest": {
		"snapshot": Required,
	},
	"google.pubsub.v1.GetSubscriptionRequest": {
		"subscription": Required,
	},
	"google.pubsub.v1.GetTopicRequest": {
		"topic": Required,
	},
	"google.pubsub.v1.IngestionDataSourceSettings": {
		"aws_kinesis":            Optional,
		"cloud_storage":          Optional,
		"azure_event_hubs":       Optional,
		"aws_msk":                Optional,
		"confluent_cloud":        Optional,
		"platform_logs_settings": Optional,
	},
	"google.pubsub.v1.IngestionDataSourceSettings.AwsKinesis": {
		"state":               OutputOnly,
		"stream_arn":          Required,
		"consumer_arn":        Required,
		"aws_role_arn":        Required,
		"gcp_service_account": Required,
	},
	"google.pubsub.v1.IngestionDataSourceSettings.AwsMsk": {
		"state":               OutputOnly,
		"cluster_arn":         Required,
		"topic":               Required,
		"aws_role_arn":        Required,
		"gcp_service_account": Required,
	},
	"google.pubsub.v1.IngestionDataSourceSettings.AzureEventHubs": {
		"state":               OutputOnly,
		"resource_group":      Optional,
		"namespace":           Optional,
		"event_hub":           Optional,
		"client_id":           Optional,
		"tenant_id":           Optional,
		"subscription_id":     Optional,
		"gcp_service_account": Optional,
	},
	"google.pubsub.v1.IngestionDataSourceSettings.CloudStorage": {
		"state":                      OutputOnly,
		"bucket":                     Optional,
		"text_format":                Optional,
		"avro_format":                Optional,
		"pubsub_avro_format":         Optional,
		"minimum_object_create_time": Optional,
		"match_glob":                 Optional,
	},
	"google.pubsub.v1.IngestionDataSourceSettings.CloudStorage.TextFormat": {
		"delimiter": Optional,
	},
	"google.pubsub.v1.IngestionDataSourceSettings.ConfluentCloud": {
		"state":               OutputOnly,
		"bootstrap_server":    Required,
		"cluster_id":          Required,
		"topic":               Required,
		"identity_pool_id":    Required,
		"gcp_service_account": Required,
	},
	"google.pubsub.v1.JavaScriptUDF": {
		"function_name": Required,
		"code":          Required,
	},
	"google.pubsub.v1.ListSchemaRevisionsRequest": {
		"name": Required,
	},
	"google.pubsub.v1.ListSchemasRequest": {
		"parent": Required,
	},
	"google.pubsub.v1.ListSnapshotsRequest": {
		"project":    Required,
		"page_size":  Optional,
		"page_token": Optional,
	},
	"google.pubsub.v1.ListSubscriptionsRequest": {
		"project":    Required,
		"page_size":  Optional,
		"page_token": Optional,
	},
	"google.pubsub.v1.ListTopicSnapshotsRequest": {
		"topic":      Required,
		"page_size":  Optional,
		"page_token": Optional,
	},
	"google.pubsub.v1.ListTopicSubscriptionsRequest": {
		"topic":      Required,
		"page_size":  Optional,
		"page_token": Optional,
	},
	"google.pubsub.v1.ListTopicsRequest": {
		"project":    Required,
		"page_size":  Optional,
		"page_token": Optional,
	},
	"google.pubsub.v1.MessageStoragePolicy": {
		"allowed_persistence_regions": Optional,
		"enforce_in_transit":          Optional,
	},
	"google.pubsub.v1.MessageTransform": {
		"javascript_udf": Optional,
		"compression":    Optional,
		"ai_inference":   Optional,
		"enabled":        Optional,
		"disabled":       Optional,
	},
	"google.pubsub.v1.ModifyAckDeadlineRequest": {
		"subscription":         Required,
		"ack_ids":              Required,
		"ack_deadline_seconds": Required,
	},
	"google.pubsub.v1.ModifyPushConfigRequest": {
		"subscription": Required,
		"push_config":  Required,
	},
	"google.pubsub.v1.PlatformLogsSettings": {
		"severity": Optional,
	},
	"google.pubsub.v1.PublishRequest": {
		"topic":    Required,
		"messages": Required,
	},
	"google.pubsub.v1.PubsubMessage": {
		"data":         Optional,
		"attributes":   Optional,
		"ordering_key": Optional,
	},
	"google.pubsub.v1.PullRequest": {
		"subscription":       Required,
		"return_immediately": Optional,
		"max_messages":       Required,
	},
	"google.pubsub.v1.PushConfig": {
		"push_endpoint":  Optional,
		"attributes":     Optional,
		"oidc_token":     Optional,
		"pubsub_wrapper": Optional,
		"no_wrapper":     Optional,
	},
	"google.pubsub.v1.PushConfig.NoWrapper": {
		"write_metadata": Optional,
	},
	"google.pubsub.v1.PushConfig.OidcToken": {
		"service_account_email": Optional,
		"audience":              Optional,
	},
	"google.pubsub.v1.RetryPolicy": {
		"minimum_backoff": Optional,
		"maximum_backoff": Optional,
	},
	"google.pubsub.v1.RollbackSchemaRequest": {
		"name":        Required,
		"revision_id": Required,
	},
	"google.pubsub.v1.Schema": {
		"name":                  Required,
		"compiled_proto_schema": Optional,
		"revision_id":           Immutable | OutputOnly,
		"revision_create_time":  OutputOnly,
	},
	"google.pubsub.v1.SchemaSettings": {
		"schema":            Required,
		"encoding":          Optional,
		"first_revision_id": Optional,
		"last_revision_id":  Optional,
	},
	"google.pubsub.v1.SeekRequest": {
		"subscription": Required,
		"time":         Optional,
		"snapshot":     Optional,
	},
	"google.pubsub.v1.Snapshot": {
		"name":        Optional,
		"topic":       Optional,
		"expire_time": Optional,
		"labels":      Optional,
	},
	"google.pubsub.v1.StreamingPullRequest": {
		"subscription":                Required,
		"ack_ids":                     Optional,
		"modify_deadline_seconds":     Optional,
		"modify_deadline_ack_ids":     Optional,
		"stream_ack_deadline_seconds": Required,
		"client_id":                   Optional,
		"max_outstanding_messages":    Optional,
		"max_outstanding_bytes":       Optional,
		"protocol_version":            Optional,
	},
	"google.pubsub.v1.Subscription": {
		"name":                             Required | Identifier,
		"topic":                            Required,
		"push_config":                      Optional,
		"bigquery_config":                  Optional,
		"cloud_storage_config":             Optional,
		"bigtable_config":                  Optional,
		"ack_deadline_seconds":             Optional,
		"retain_acked_messages":            Optional,
		"message_retention_duration":       Optional,
		"labels":                           Optional,
		"enable_message_ordering":          Optional,
		"expiration_policy":                Optional,
		"filter":                           Optional,
		"dead_letter_policy":               Optional,
		"retry_policy":                     Optional,
		"detached":                         Optional,
		"enable_exactly_once_delivery":     Optional,
		"topic_message_retention_duration": OutputOnly,
		"state":                            OutputOnly,
		"analytics_hub_subscription_info":  OutputOnly,
		"message_transforms":               Optional,
		"tags":                             InputOnly | Immutable | Optional,
	},
	"google.pubsub.v1.Subscription.AnalyticsHubSubscriptionInfo": {
		"listing":      Optional,
		"subscription": Optional,
	},
	"google.pubsub.v1.Topic": {
		"name":                           Required | Identifier,
		"labels":                         Optional,
		"message_storage_policy":         Optional,
		"kms_key_name":                   Optional,
		"schema_settings":                Optional,
		"satisfies_pzs":                  Optional,
		"message_retention_duration":     Optional,
		"state":                          OutputOnly,
		"ingestion_data_source_settings": Optional,
		"message_transforms":             Optional,
		"tags":                           InputOnly | Immutable | Optional,
	},
	"google.pubsub.v1.UpdateSnapshotRequest": {
		"snapshot":    Required,
		"update_mask": Required,
	},
	"google.pubsub.v1.UpdateSubscriptionRequest": {
		"subscription": Required,
		"update_mask":  Required,
	},
	"google.pubsub.v1.UpdateTopicRequest": {
		"topic":       Required,
		"update_mask": Required,
	},
	"google.pubsub.v1.ValidateMessageRequest": {
		"parent": Required,
	},
	"google.pubsub.v1.ValidateSchemaRequest": {
		"parent": Required,
		"schema": Required,
	},
}
